export interface LearningPathStep {
  stepNumber: number;
  level: number;
  moduleId: string;
  titleEn: string;
  titleId: string;
  descEn: string;
  descId: string;
  theoryHref: string;
  labId?: string;
  labName?: string;
  keyEquation?: string;
  prerequisites: string[];
}

export interface LearningPath {
  id: string;
  slug: string;
  titleEn: string;
  titleId: string;
  subtitleEn: string;
  subtitleId: string;
  descriptionEn: string;
  descriptionId: string;
  estimatedHours: number;
  badge: string;
  icon: string;
  colorGradient: string;
  steps: LearningPathStep[];
}

export const LEARNING_PATHS: LearningPath[] = [
  {
    id: 'slam-navigation',
    slug: 'slam-navigation',
    titleEn: 'SLAM & Autonomous Mobile Robot Navigation',
    titleId: 'SLAM & Navigasi Otonom Robot Bergerak',
    subtitleEn: 'End-to-End Autonomous Mobile Robotics Pipeline',
    subtitleId: 'Alur Penuh Navigasi Otonom & Pemetaan Spasial',
    descriptionEn:
      'Master the complete pipeline of autonomous mobile robotics: from vector spaces, coordinate transforms, differential kinematics, and LiDAR raycasting, to Bayesian filters, occupancy grid mapping, ICP scan matching, A* planning, and Pure Pursuit tracking.',
    descriptionId:
      'Kuasai alur lengkap robotika bergerak otonom: dari ruang vektor, transformasi koordinat, kinematika roda diferensial, dan raycasting LiDAR, hingga filter Bayesian, pemetaan grid okupansi, pencocokan pindaian ICP, perencanaan A*, dan kendali Pure Pursuit.',
    estimatedHours: 24,
    badge: 'Flagship Path',
    icon: '🧭',
    colorGradient: 'from-cyan-500/20 via-blue-600/15 to-indigo-600/20',
    steps: [
      {
        stepNumber: 1,
        level: 1,
        moduleId: 'vectors-and-coordinate-geometry',
        titleEn: 'Vector Geometry & Euclidean Metrics',
        titleId: 'Geometri Vektor & Metrik Euclidean',
        descEn: 'Represent physical positions, displacements, and Euclidean norms ||v||.',
        descId: 'Representasikan posisi fisik, perpindahan, dan magnitudo Euclidean ||v||.',
        theoryHref: '/learn/mathematics/vectors-and-coordinate-geometry',
        labId: 'vector-explorer',
        labName: 'Vector Explorer Lab',
        keyEquation: '\\|\\mathbf{v}\\| = \\sqrt{v_x^2 + v_y^2}',
        prerequisites: ['Level 0 Orientation'],
      },
      {
        stepNumber: 2,
        level: 2,
        moduleId: 'coordinate-frames-and-transforms',
        titleEn: 'Coordinate Frames & Rigid SE(2) Transforms',
        titleId: 'Kerangka Koordinat & Transformasi SE(2)',
        descEn: 'Map coordinates between World {W}, Robot Base {B}, and Sensor {S} frames.',
        descId: 'Transformasi koordinat antara kerangka Dunia {W}, Basis Robot {B}, dan Sensor {S}.',
        theoryHref: '/learn/geometry/coordinate-frames-and-transforms',
        labId: 'transforms-2d',
        labName: '2D Transforms Sandbox',
        keyEquation: '\\mathbf{p}^W = \\mathbf{R}(\\theta) \\mathbf{p}^B + \\mathbf{t}',
        prerequisites: ['Vector Geometry'],
      },
      {
        stepNumber: 3,
        level: 3,
        moduleId: 'differential-drive-kinematics',
        titleEn: 'Differential-Drive Unicycle Kinematics',
        titleId: 'Kinematika Unicycle Roda Diferensial',
        descEn: 'Compute Instantaneous Center of Curvature (ICC) and handle non-holonomic constraints.',
        descId: 'Hitung Pusat Kurvatur Seketika (ICC) dan kendala non-holonomik tanpa selip.',
        theoryHref: '/learn/kinematics/differential-drive-kinematics',
        labId: 'kinematics-2d',
        labName: 'Differential Drive Simulator',
        keyEquation: 'R_{\\text{ICC}} = \\frac{L}{2} \\frac{v_R + v_L}{v_R - v_L}',
        prerequisites: ['Coordinate Frames'],
      },
      {
        stepNumber: 4,
        level: 5,
        moduleId: 'lidar-raycasting',
        titleEn: 'LiDAR Raycasting & Point Cloud Extraction',
        titleId: 'Raycasting LiDAR & Ekstraksi Point Cloud',
        descEn: 'Model 360° Time-of-Flight (ToF) laser pulses and compute parametric line intersections.',
        descId: 'Modelkan pulsa laser Time-of-Flight (ToF) 360° dan perpotongan garis parametrik.',
        theoryHref: '/learn/sensors/lidar-raycasting',
        labId: 'lidar-raycast',
        labName: 'LiDAR Raycasting Lab',
        keyEquation: 'd = \\frac{c \\cdot \\Delta t}{2}',
        prerequisites: ['SE(2) Transforms'],
      },
      {
        stepNumber: 5,
        level: 5,
        moduleId: 'wheel-odometry-and-drift',
        titleEn: 'Wheel Odometry & Dead Reckoning Drift',
        titleId: 'Odometri Roda & Akumulasi Galat Drift',
        descEn: 'Integrate wheel encoder pulses and analyze systematic heading divergence over time.',
        descId: 'Integrasikan pulsa enkoder roda dan amati divergensi galat sudut hadap.',
        theoryHref: '/learn/sensors/wheel-odometry-and-drift',
        labId: 'wheel-odometry',
        labName: 'Odometry Drift Lab',
        keyEquation: '\\Delta\\theta = \\frac{\\Delta s_R - \\Delta s_L}{L}',
        prerequisites: ['Differential Drive Kinematics'],
      },
      {
        stepNumber: 6,
        level: 8,
        moduleId: 'mcl-particle-filter',
        titleEn: 'Monte Carlo Localization (MCL) Particle Filter',
        titleId: 'Filter Partikel Monte Carlo Localization',
        descEn: 'Fuse odometry prediction with noisy LiDAR likelihood to maintain multimodal belief.',
        descId: 'Gabungkan prediksi odometri dengan likelihood sensor untuk mengestimasi posisi robot.',
        theoryHref: '/learn/estimation/mcl-particle-filter',
        labId: 'mcl-localization',
        labName: 'Particle Filter Localization Lab',
        keyEquation: 'w_t^{[m]} \\propto p(z_t \\mid x_t^{[m]})',
        prerequisites: ['LiDAR Raycasting', 'Wheel Odometry'],
      },
      {
        stepNumber: 7,
        level: 9,
        moduleId: 'occupancy-grid-mapping',
        titleEn: 'Log-Odds Occupancy Grid Mapping',
        titleId: 'Pemetaan Grid Okupansi Log-Odds',
        descEn: 'Construct probabilistic grid maps from laser raycasts using recursive log-odds updates.',
        descId: 'Bangun peta probabilitas grid dari pindaian laser dengan pembaruan log-odds aditif.',
        theoryHref: '/learn/perception/occupancy-grid-mapping',
        labId: 'occupancy-mapping',
        labName: 'Log-Odds Mapping Lab',
        keyEquation: 'l_t(m_i) = l_{t-1}(m_i) + \\text{inv\\_sensor}(m_i, z_t) - l_0',
        prerequisites: ['LiDAR Raycasting', 'MCL Localization'],
      },
      {
        stepNumber: 8,
        level: 10,
        moduleId: 'icp-scan-matching',
        titleEn: 'Iterative Closest Point (ICP) SLAM',
        titleId: 'Pencocokan Pindaian ICP & SLAM',
        descEn: 'Align consecutive LiDAR point clouds analytically using Singular Value Decomposition (SVD).',
        descId: 'Selaraskan pindaian laser berurutan secara analitik menggunakan dekomposisi SVD.',
        theoryHref: '/learn/advanced/icp-scan-matching',
        labId: 'icp-slam',
        labName: 'ICP Point Cloud SLAM Lab',
        keyEquation: '\\min_{\\mathbf{R}, \\mathbf{t}} \\sum_{i=1}^N \\|\\mathbf{R}\\mathbf{p}_i + \\mathbf{t} - \\mathbf{q}_i\\|^2',
        prerequisites: ['Occupancy Grid Mapping'],
      },
      {
        stepNumber: 9,
        level: 6,
        moduleId: 'a-star',
        titleEn: 'A* Heuristic Path Planning & C-Space',
        titleId: 'Perencanaan Jalur Heuristik A* & C-Space',
        descEn: 'Expand obstacles by robot radius and find optimal collision-free shortest paths.',
        descId: 'Perluas rintangan dengan radius robot dan temukan jalur optimal terpendek bebas tabrakan.',
        theoryHref: '/learn/planning/a-star',
        labId: 'a-star-planning',
        labName: 'A* Path Search Lab',
        keyEquation: 'f(n) = g(n) + h(n)',
        prerequisites: ['Occupancy Grid Mapping'],
      },
      {
        stepNumber: 10,
        level: 7,
        moduleId: 'pure-pursuit-path-tracking',
        titleEn: 'Pure Pursuit Geometric Motion Control',
        titleId: 'Kendali Kemudi Geometris Pure Pursuit',
        descEn: 'Calculate curvature steering commands to track planned waypoints at designated speeds.',
        descId: 'Hitung perintah kurvatur kemudi untuk melacak jalur referensi dengan stabil.',
        theoryHref: '/learn/control/pure-pursuit-path-tracking',
        labId: 'pure-pursuit',
        labName: 'Pure Pursuit Tracking Lab',
        keyEquation: '\\kappa = \\frac{2\\sin\\alpha}{L_d}, \\quad \\delta = \\arctan(\\kappa L)',
        prerequisites: ['A* Path Planning', 'Differential Kinematics'],
      },
    ],
  },
  {
    id: 'manipulation-arms',
    slug: 'manipulation-arms',
    titleEn: 'Articulated Robotic Arm Manipulation',
    titleId: 'Manipulasi & Kinematika Lengan Robot',
    subtitleEn: 'Spatial Kinematics, Jacobians & Singularity Avoidance',
    subtitleId: 'Kinematika Spasial, Jacobian & Pencegahan Singularitas',
    descriptionEn:
      'Learn the foundations of robot arms: from homogeneous frame trees and Denavit-Hartenberg parameters to forward/inverse kinematics, velocity ellipsoids, and singular posture avoidance.',
    descriptionId:
      'Pelajari fondasi lengan robotik: dari rantai kerangka homogen dan parameter DH hingga kinematika maju/invers, elips kecepatan, dan pencegahan postur singularitas.',
    estimatedHours: 16,
    badge: 'Articulated Arms',
    icon: '🦾',
    colorGradient: 'from-amber-500/20 via-orange-600/15 to-rose-600/20',
    steps: [
      {
        stepNumber: 1,
        level: 2,
        moduleId: 'transform-composition-and-chains',
        titleEn: 'Homogeneous Transforms & Kinematic Chains',
        titleId: 'Transformasi Homogen & Rantai Kinematik',
        descEn: 'Chain coordinate frames along links from arm base to end-effector.',
        descId: 'Rangkai kerangka koordinat dari pangkal lengan hingga ujung efektor.',
        theoryHref: '/learn/geometry/transform-composition-and-chains',
        labId: 'transform-composition',
        labName: 'Transform Chaining Lab',
        keyEquation: '\\mathbf{T}_0^n = \\mathbf{T}_0^1 \\mathbf{T}_1^2 \\dots \\mathbf{T}_{n-1}^n',
        prerequisites: ['Vector Geometry'],
      },
      {
        stepNumber: 2,
        level: 14,
        moduleId: '2dof-forward-kinematics',
        titleEn: '2-DOF Planar Forward Kinematics (FK)',
        titleId: 'Kinematika Maju (FK) Lengan 2-DOF',
        descEn: 'Compute Cartesian end-effector coordinates from given joint angles (θ₁, θ₂).',
        descId: 'Hitung koordinat ujung efektor dari sudut sendi motor (θ₁, θ₂).',
        theoryHref: '/learn/manipulation/2dof-forward-kinematics',
        labId: 'arm-2dof-fk',
        labName: 'Arm FK & Workspace Lab',
        keyEquation: 'x = L_1\\cos\\theta_1 + L_2\\cos(\\theta_1 + \\theta_2)',
        prerequisites: ['Transform Chaining'],
      },
      {
        stepNumber: 3,
        level: 14,
        moduleId: '2dof-inverse-kinematics',
        titleEn: 'Analytical Inverse Kinematics (IK)',
        titleId: 'Kinematika Invers (IK) Analitik',
        descEn: 'Solve joint angles from target Cartesian coordinates using the Law of Cosines.',
        descId: 'Hitung sudut sendi dari target koordinat Kartesius menggunakan Hukum Kosinus.',
        theoryHref: '/learn/manipulation/2dof-inverse-kinematics',
        labId: 'arm-2dof-ik',
        labName: 'Arm IK Solver Lab',
        keyEquation: '\\cos\\theta_2 = \\frac{x^2 + y^2 - L_1^2 - L_2^2}{2 L_1 L_2}',
        prerequisites: ['Forward Kinematics'],
      },
      {
        stepNumber: 4,
        level: 14,
        moduleId: 'jacobian-and-singularity',
        titleEn: 'Jacobian Matrix & Velocity Ellipsoids',
        titleId: 'Matriks Jacobian & Elips Kecepatan',
        descEn: 'Map joint velocities to end-effector Cartesian velocities and detect singularities.',
        descId: 'Petakan kecepatan sudut sendi ke kecepatan ujung lengan dan deteksi singularitas.',
        theoryHref: '/learn/manipulation/jacobian-and-singularity',
        labId: 'jacobian-singularity',
        labName: 'Jacobian Singularity Lab',
        keyEquation: '\\dot{\\mathbf{x}} = \\mathbf{J}(\\boldsymbol{\\theta}) \\dot{\\boldsymbol{\\theta}}, \\quad \\det(\\mathbf{J}) = 0',
        prerequisites: ['Analytical IK'],
      },
    ],
  },
  {
    id: 'dynamics-control',
    slug: 'dynamics-control',
    titleEn: 'Control Systems & State-Space Dynamics',
    titleId: 'Sistem Kendali & Dinamika Ruang Status',
    subtitleEn: 'Continuous & Discrete-Time Closed-Loop Feedback Control',
    subtitleId: 'Kendali Umpan Balik Simpal Tertutup Kontinu & Diskret',
    descriptionEn:
      'Understand the mathematical principles of robot motion control: state-space models, numerical integration (Euler vs RK4), PID loop tuning, and multi-agent swarm consensus.',
    descriptionId:
      'Pahami prinsip matematika kendali gerak robot: model ruang status, integrasi numerik (Euler vs RK4), tuning loop PID, dan konsensus kawanan multi-agent.',
    estimatedHours: 18,
    badge: 'Control Theory',
    icon: '🎛️',
    colorGradient: 'from-emerald-500/20 via-teal-600/15 to-cyan-600/20',
    steps: [
      {
        stepNumber: 1,
        level: 7,
        moduleId: 'state-space-and-feedback',
        titleEn: 'State-Space Modeling & Phase Portraits',
        titleId: 'Pemodelan Ruang Status & Diagram Fase',
        descEn: 'Formulate second-order dynamical systems into linear state-space dx/dt = Ax + Bu.',
        descId: 'Formulasikan dinamika orde-dua ke dalam bentuk matriks ruang status dx/dt = Ax + Bu.',
        theoryHref: '/learn/control/state-space-and-feedback',
        labId: 'state-space',
        labName: 'State-Space Phase Plane Lab',
        keyEquation: '\\dot{\\mathbf{x}} = \\mathbf{A}\\mathbf{x} + \\mathbf{B}\\mathbf{u}',
        prerequisites: ['Vector Geometry'],
      },
      {
        stepNumber: 2,
        level: 7,
        moduleId: 'discrete-time-simulation',
        titleEn: 'Discrete Simulation: Euler vs Runge-Kutta 4 (RK4)',
        titleId: 'Simulasi Waktu Diskret: Euler vs RK4',
        descEn: 'Compare numerical stability and energy drift across Euler, Midpoint, and RK4 solvers.',
        descId: 'Bandingkan stabilitas numerik dan divergensi energi antara solver Euler dan RK4.',
        theoryHref: '/learn/control/discrete-time-simulation',
        labId: 'discrete-simulation',
        labName: 'Numerical Solvers Lab',
        keyEquation: 'x_{k+1} = x_k + \\frac{\\Delta t}{6}(k_1 + 2k_2 + 2k_3 + k_4)',
        prerequisites: ['State-Space Modeling'],
      },
      {
        stepNumber: 3,
        level: 7,
        moduleId: 'pid-and-lqr-control',
        titleEn: 'PID Feedback Control & Step Response',
        titleId: 'Kendali Umpan Balik PID & Respon Step',
        descEn: 'Tune Kp, Ki, and Kd gains to achieve critical damping without excessive overshoot.',
        descId: 'Tuning penguatan Kp, Ki, dan Kd untuk mencapai redaman kritis tanpa lonjakan berlebih.',
        theoryHref: '/learn/control/pid-and-lqr-control',
        labId: 'pid-tuning',
        labName: 'PID Tuning Lab',
        keyEquation: 'u(t) = K_p e(t) + K_i \\int_0^t e(\\tau)d\\tau + K_d \\dot{e}(t)',
        prerequisites: ['Discrete Simulation'],
      },
      {
        stepNumber: 4,
        level: 18,
        moduleId: 'laplacian-consensus',
        titleEn: 'Multi-Agent Graph Laplacian Consensus',
        titleId: 'Konsensus Graf Laplacian Kawanan Multi-Agent',
        descEn: 'Coordinate decentralized multi-robot swarms using communication graph Laplacians.',
        descId: 'Koordinasikan kawanan robot terdesentralisasi menggunakan matriks Laplacian komunikasi.',
        theoryHref: '/learn/advanced/laplacian-consensus',
        labId: 'multi-agent-swarm',
        labName: 'Swarm Consensus Lab',
        keyEquation: '\\dot{\\mathbf{x}} = -\\mathbf{L} \\mathbf{x}',
        prerequisites: ['PID Control', 'State-Space Modeling'],
      },
    ],
  },
];
