export interface LearningPathStep {
  stepNumber: number;
  level: number;
  moduleId: string;
  titleEn: string;
  titleId: string;
  descEn: string;
  descId: string;
  theoryHref: string;
  labId?: string;
  labName?: string;
  keyEquation?: string;
  prerequisites: string[];
}

export interface LearningPath {
  id: string;
  slug: string;
  titleEn: string;
  titleId: string;
  subtitleEn: string;
  subtitleId: string;
  descriptionEn: string;
  descriptionId: string;
  estimatedHours: number;
  badge: string;
  icon: string;
  colorGradient: string;
  steps: LearningPathStep[];
}

export const LEARNING_PATHS: LearningPath[] = [
  {
    id: 'slam-navigation',
    slug: 'slam-navigation',
    titleEn: 'SLAM & Autonomous Mobile Robot Navigation',
    titleId: 'SLAM & Navigasi Otonom Robot Bergerak',
    subtitleEn: 'End-to-End Autonomous Mobile Robotics Pipeline',
    subtitleId: 'Alur Penuh Navigasi Otonom & Pemetaan Spasial',
    descriptionEn:
      'Master the complete pipeline of autonomous mobile robotics: from vector spaces, coordinate transforms, differential kinematics, and LiDAR raycasting, to Bayesian filters, occupancy grid mapping, ICP scan matching, A* planning, and Pure Pursuit tracking.',
    descriptionId:
      'Kuasai alur lengkap robotika bergerak otonom: dari ruang vektor, transformasi koordinat, kinematika roda diferensial, dan raycasting LiDAR, hingga filter Bayesian, pemetaan grid okupansi, pencocokan pindaian ICP, perencanaan A*, dan kendali Pure Pursuit.',
    estimatedHours: 24,
    badge: 'Flagship Track',
    icon: '🧭',
    colorGradient: 'from-cyan-500/20 via-blue-600/15 to-indigo-600/20',
    steps: [
      {
        stepNumber: 1,
        level: 1,
        moduleId: 'vectors-and-coordinate-geometry',
        titleEn: 'Vector Geometry & Euclidean Metrics',
        titleId: 'Geometri Vektor & Metrik Euclidean',
        descEn: 'Represent physical positions, displacements, and Euclidean norms ||v||.',
        descId: 'Representasikan posisi fisik, perpindahan, dan magnitudo Euclidean ||v||.',
        theoryHref: '/learn/mathematics/vectors-and-coordinate-geometry',
        labId: 'vector-explorer',
        labName: 'Vector Explorer Lab',
        keyEquation: '\\|\\mathbf{v}\\| = \\sqrt{v_x^2 + v_y^2}',
        prerequisites: ['Level 0 Orientation'],
      },
      {
        stepNumber: 2,
        level: 2,
        moduleId: 'coordinate-frames-and-transforms',
        titleEn: 'Coordinate Frames & Rigid SE(2) Transforms',
        titleId: 'Kerangka Koordinat & Transformasi SE(2)',
        descEn: 'Map coordinates between World {W}, Robot Base {B}, and Sensor {S} frames.',
        descId: 'Transformasi koordinat antara kerangka Dunia {W}, Basis Robot {B}, dan Sensor {S}.',
        theoryHref: '/learn/geometry/coordinate-frames-and-transforms',
        labId: 'transforms-2d',
        labName: '2D Transforms Sandbox',
        keyEquation: '\\mathbf{p}^W = \\mathbf{R}(\\theta) \\mathbf{p}^B + \\mathbf{t}',
        prerequisites: ['Vector Geometry'],
      },
      {
        stepNumber: 3,
        level: 3,
        moduleId: 'differential-drive-kinematics',
        titleEn: 'Differential-Drive Unicycle Kinematics',
        titleId: 'Kinematika Unicycle Roda Diferensial',
        descEn: 'Compute Instantaneous Center of Curvature (ICC) and handle non-holonomic constraints.',
        descId: 'Hitung Pusat Kurvatur Seketika (ICC) dan kendala non-holonomik tanpa selip.',
        theoryHref: '/learn/kinematics/differential-drive-kinematics',
        labId: 'kinematics-2d',
        labName: 'Differential Drive Simulator',
        keyEquation: 'R_{\\text{ICC}} = \\frac{L}{2} \\frac{v_R + v_L}{v_R - v_L}',
        prerequisites: ['Coordinate Frames'],
      },
      {
        stepNumber: 4,
        level: 5,
        moduleId: 'lidar-raycasting',
        titleEn: 'LiDAR Raycasting & Point Cloud Extraction',
        titleId: 'Raycasting LiDAR & Ekstraksi Point Cloud',
        descEn: 'Model 360° Time-of-Flight (ToF) laser pulses and compute parametric line intersections.',
        descId: 'Modelkan pulsa laser Time-of-Flight (ToF) 360° dan perpotongan garis parametrik.',
        theoryHref: '/learn/sensors/lidar-raycasting',
        labId: 'lidar-raycast',
        labName: 'LiDAR Raycasting Lab',
        keyEquation: 'd = \\frac{c \\cdot \\Delta t}{2}',
        prerequisites: ['SE(2) Transforms'],
      },
      {
        stepNumber: 5,
        level: 5,
        moduleId: 'wheel-odometry-and-drift',
        titleEn: 'Wheel Odometry & Dead Reckoning Drift',
        titleId: 'Odometri Roda & Akumulasi Galat Drift',
        descEn: 'Integrate wheel encoder pulses and analyze systematic heading divergence over time.',
        descId: 'Integrasikan pulsa enkoder roda dan amati divergensi galat sudut hadap.',
        theoryHref: '/learn/sensors/wheel-odometry-and-drift',
        labId: 'wheel-odometry',
        labName: 'Odometry Drift Lab',
        keyEquation: '\\Delta\\theta = \\frac{\\Delta s_R - \\Delta s_L}{L}',
        prerequisites: ['Differential Drive Kinematics'],
      },
      {
        stepNumber: 6,
        level: 8,
        moduleId: 'mcl-particle-filter',
        titleEn: 'Monte Carlo Localization (MCL) Particle Filter',
        titleId: 'Filter Partikel Monte Carlo Localization',
        descEn: 'Fuse odometry prediction with noisy LiDAR likelihood to maintain multimodal belief.',
        descId: 'Gabungkan prediksi odometri dengan likelihood sensor untuk mengestimasi posisi robot.',
        theoryHref: '/learn/estimation/mcl-particle-filter',
        labId: 'mcl-localization',
        labName: 'Particle Filter Localization Lab',
        keyEquation: 'w_t^{[m]} \\propto p(z_t \\mid x_t^{[m]})',
        prerequisites: ['LiDAR Raycasting', 'Wheel Odometry'],
      },
      {
        stepNumber: 7,
        level: 9,
        moduleId: 'occupancy-grid-mapping',
        titleEn: 'Log-Odds Occupancy Grid Mapping',
        titleId: 'Pemetaan Grid Okupansi Log-Odds',
        descEn: 'Construct probabilistic grid maps from laser raycasts using recursive log-odds updates.',
        descId: 'Bangun peta probabilitas grid dari pindaian laser dengan pembaruan log-odds aditif.',
        theoryHref: '/learn/perception/occupancy-grid-mapping',
        labId: 'occupancy-mapping',
        labName: 'Log-Odds Mapping Lab',
        keyEquation: 'l_t(m_i) = l_{t-1}(m_i) + \\text{inv\\_sensor}(m_i, z_t) - l_0',
        prerequisites: ['LiDAR Raycasting', 'MCL Localization'],
      },
      {
        stepNumber: 8,
        level: 10,
        moduleId: 'icp-scan-matching',
        titleEn: 'Iterative Closest Point (ICP) SLAM',
        titleId: 'Pencocokan Pindaian ICP & SLAM',
        descEn: 'Align consecutive LiDAR point clouds analytically using Singular Value Decomposition (SVD).',
        descId: 'Selaraskan pindaian laser berurutan secara analitik menggunakan dekomposisi SVD.',
        theoryHref: '/learn/advanced/icp-scan-matching',
        labId: 'icp-slam',
        labName: 'ICP Point Cloud SLAM Lab',
        keyEquation: '\\min_{\\mathbf{R}, \\mathbf{t}} \\sum_{i=1}^N \\|\\mathbf{R}\\mathbf{p}_i + \\mathbf{t} - \\mathbf{q}_i\\|^2',
        prerequisites: ['Occupancy Grid Mapping'],
      },
      {
        stepNumber: 9,
        level: 6,
        moduleId: 'a-star',
        titleEn: 'A* Heuristic Path Planning & C-Space',
        titleId: 'Perencanaan Jalur Heuristik A* & C-Space',
        descEn: 'Expand obstacles by robot radius and find optimal collision-free shortest paths.',
        descId: 'Perluas rintangan dengan radius robot dan temukan jalur optimal terpendek bebas tabrakan.',
        theoryHref: '/learn/planning/a-star',
        labId: 'a-star-planning',
        labName: 'A* Path Search Lab',
        keyEquation: 'f(n) = g(n) + h(n)',
        prerequisites: ['Occupancy Grid Mapping'],
      },
      {
        stepNumber: 10,
        level: 7,
        moduleId: 'pure-pursuit-path-tracking',
        titleEn: 'Pure Pursuit Geometric Motion Control',
        titleId: 'Kendali Kemudi Geometris Pure Pursuit',
        descEn: 'Calculate curvature steering commands to track planned waypoints at designated speeds.',
        descId: 'Hitung perintah kurvatur kemudi untuk melacak jalur referensi dengan stabil.',
        theoryHref: '/learn/control/pure-pursuit-path-tracking',
        labId: 'pure-pursuit',
        labName: 'Pure Pursuit Tracking Lab',
        keyEquation: '\\kappa = \\frac{2\\sin\\alpha}{L_d}, \\quad \\delta = \\arctan(\\kappa L)',
        prerequisites: ['A* Path Planning', 'Differential Kinematics'],
      },
    ],
  },
  {
    id: 'manipulation-arms',
    slug: 'manipulation-arms',
    titleEn: 'Articulated Robotic Arm Manipulation',
    titleId: 'Manipulasi & Kinematika Lengan Robot',
    subtitleEn: 'Spatial Kinematics, Jacobians & Singularity Avoidance',
    subtitleId: 'Kinematika Spasial, Jacobian & Pencegahan Singularitas',
    descriptionEn:
      'Learn the foundations of robot arms: from homogeneous frame trees and Denavit-Hartenberg parameters to forward/inverse kinematics, velocity ellipsoids, and singular posture avoidance.',
    descriptionId:
      'Pelajari fondasi lengan robotik: dari rantai kerangka homogen dan parameter DH hingga kinematika maju/invers, elips kecepatan, dan pencegahan postur singularitas.',
    estimatedHours: 16,
    badge: 'Articulated Arms',
    icon: '🦾',
    colorGradient: 'from-amber-500/20 via-orange-600/15 to-rose-600/20',
    steps: [
      {
        stepNumber: 1,
        level: 2,
        moduleId: 'transform-composition-and-chains',
        titleEn: 'Homogeneous Transforms & Kinematic Chains',
        titleId: 'Transformasi Homogen & Rantai Kinematik',
        descEn: 'Chain coordinate frames along links from arm base to end-effector.',
        descId: 'Rangkai kerangka koordinat dari pangkal lengan hingga ujung efektor.',
        theoryHref: '/learn/geometry/transform-composition-and-chains',
        labId: 'transform-composition',
        labName: 'Transform Chaining Lab',
        keyEquation: '\\mathbf{T}_0^n = \\mathbf{T}_0^1 \\mathbf{T}_1^2 \\dots \\mathbf{T}_{n-1}^n',
        prerequisites: ['Vector Geometry'],
      },
      {
        stepNumber: 2,
        level: 14,
        moduleId: '2dof-forward-kinematics',
        titleEn: '2-DOF Planar Forward Kinematics (FK)',
        titleId: 'Kinematika Maju (FK) Lengan 2-DOF',
        descEn: 'Compute Cartesian end-effector coordinates from given joint angles (θ₁, θ₂).',
        descId: 'Hitung koordinat ujung efektor dari sudut sendi motor (θ₁, θ₂).',
        theoryHref: '/learn/manipulation/2dof-forward-kinematics',
        labId: 'arm-2dof-fk',
        labName: 'Arm FK & Workspace Lab',
        keyEquation: 'x = L_1\\cos\\theta_1 + L_2\\cos(\\theta_1 + \\theta_2)',
        prerequisites: ['Transform Chaining'],
      },
      {
        stepNumber: 3,
        level: 14,
        moduleId: '2dof-inverse-kinematics',
        titleEn: 'Analytical Inverse Kinematics (IK)',
        titleId: 'Kinematika Invers (IK) Analitik',
        descEn: 'Solve joint angles from target Cartesian coordinates using the Law of Cosines.',
        descId: 'Hitung sudut sendi dari target koordinat Kartesius menggunakan Hukum Kosinus.',
        theoryHref: '/learn/manipulation/2dof-inverse-kinematics',
        labId: 'arm-2dof-ik',
        labName: 'Arm IK Solver Lab',
        keyEquation: '\\cos\\theta_2 = \\frac{x^2 + y^2 - L_1^2 - L_2^2}{2 L_1 L_2}',
        prerequisites: ['Forward Kinematics'],
      },
      {
        stepNumber: 4,
        level: 14,
        moduleId: 'jacobian-and-singularity',
        titleEn: 'Jacobian Matrix & Velocity Ellipsoids',
        titleId: 'Matriks Jacobian & Elips Kecepatan',
        descEn: 'Map joint velocities to end-effector Cartesian velocities and detect singularities.',
        descId: 'Petakan kecepatan sudut sendi ke kecepatan ujung lengan dan deteksi singularitas.',
        theoryHref: '/learn/manipulation/jacobian-and-singularity',
        labId: 'jacobian-singularity',
        labName: 'Jacobian Singularity Lab',
        keyEquation: '\\dot{\\mathbf{x}} = \\mathbf{J}(\\boldsymbol{\\theta}) \\dot{\\boldsymbol{\\theta}}, \\quad \\det(\\mathbf{J}) = 0',
        prerequisites: ['Analytical IK'],
      },
    ],
  },
  {
    id: 'dynamics-control',
    slug: 'dynamics-control',
    titleEn: 'Control Systems & State-Space Dynamics',
    titleId: 'Sistem Kendali & Dinamika Ruang Status',
    subtitleEn: 'Continuous & Discrete-Time Closed-Loop Feedback Control',
    subtitleId: 'Kendali Umpan Balik Simpal Tertutup Kontinu & Diskret',
    descriptionEn:
      'Understand the mathematical principles of robot motion control: state-space models, numerical integration (Euler vs RK4), PID loop tuning, and multi-agent swarm consensus.',
    descriptionId:
      'Pahami prinsip matematika kendali gerak robot: model ruang status, integrasi numerik (Euler vs RK4), tuning loop PID, dan konsensus kawanan multi-agent.',
    estimatedHours: 18,
    badge: 'Control Theory',
    icon: '🎛️',
    colorGradient: 'from-emerald-500/20 via-teal-600/15 to-cyan-600/20',
    steps: [
      {
        stepNumber: 1,
        level: 7,
        moduleId: 'state-space-and-feedback',
        titleEn: 'State-Space Modeling & Phase Portraits',
        titleId: 'Pemodelan Ruang Status & Diagram Fase',
        descEn: 'Formulate second-order dynamical systems into linear state-space dx/dt = Ax + Bu.',
        descId: 'Formulasikan dinamika orde-dua ke dalam bentuk matriks ruang status dx/dt = Ax + Bu.',
        theoryHref: '/learn/control/state-space-and-feedback',
        labId: 'state-space',
        labName: 'State-Space Phase Plane Lab',
        keyEquation: '\\dot{\\mathbf{x}} = \\mathbf{A}\\mathbf{x} + \\mathbf{B}\\mathbf{u}',
        prerequisites: ['Vector Geometry'],
      },
      {
        stepNumber: 2,
        level: 7,
        moduleId: 'discrete-time-simulation',
        titleEn: 'Discrete Simulation: Euler vs Runge-Kutta 4 (RK4)',
        titleId: 'Simulasi Waktu Diskret: Euler vs RK4',
        descEn: 'Compare numerical stability and energy drift across Euler, Midpoint, and RK4 solvers.',
        descId: 'Bandingkan stabilitas numerik dan divergensi energi antara solver Euler dan RK4.',
        theoryHref: '/learn/control/discrete-time-simulation',
        labId: 'discrete-simulation',
        labName: 'Numerical Solvers Lab',
        keyEquation: 'x_{k+1} = x_k + \\frac{\\Delta t}{6}(k_1 + 2k_2 + 2k_3 + k_4)',
        prerequisites: ['State-Space Modeling'],
      },
      {
        stepNumber: 3,
        level: 7,
        moduleId: 'pid-and-lqr-control',
        titleEn: 'PID Feedback Control & Step Response',
        titleId: 'Kendali Umpan Balik PID & Respon Step',
        descEn: 'Tune Kp, Ki, and Kd gains to achieve critical damping without excessive overshoot.',
        descId: 'Tuning penguatan Kp, Ki, dan Kd untuk mencapai redaman kritis tanpa lonjakan berlebih.',
        theoryHref: '/learn/control/pid-and-lqr-control',
        labId: 'pid-tuning',
        labName: 'PID Tuning Lab',
        keyEquation: 'u(t) = K_p e(t) + K_i \\int_0^t e(\\tau)d\\tau + K_d \\dot{e}(t)',
        prerequisites: ['Discrete Simulation'],
      },
      {
        stepNumber: 4,
        level: 18,
        moduleId: 'laplacian-consensus',
        titleEn: 'Multi-Agent Graph Laplacian Consensus',
        titleId: 'Konsensus Graf Laplacian Kawanan Multi-Agent',
        descEn: 'Coordinate decentralized multi-robot swarms using communication graph Laplacians.',
        descId: 'Koordinasikan kawanan robot terdesentralisasi menggunakan matriks Laplacian komunikasi.',
        theoryHref: '/learn/advanced/laplacian-consensus',
        labId: 'multi-agent-swarm',
        labName: 'Swarm Consensus Lab',
        keyEquation: '\\dot{\\mathbf{x}} = -\\mathbf{L} \\mathbf{x}',
        prerequisites: ['PID Control', 'State-Space Modeling'],
      },
    ],
  },
  {
    id: 'spatial-geometry',
    slug: 'spatial-geometry',
    titleEn: 'Spatial Geometry & Coordinate Transforms',
    titleId: 'Geometri Spasial & Transformasi Koordinat',
    subtitleEn: '2D/3D Frames, Rotations, Homogeneous Transforms & Chaining',
    subtitleId: 'Kerangka 2D/3D, Rotasi, Transformasi Homogen & Perantaian',
    descriptionEn:
      'Master the foundational mathematics that describes robot poses in 2D and 3D Euclidean space: vectors, direction cosines, SO(2)/SO(3) rotations, and rigid SE(2)/SE(3) transform chains.',
    descriptionId:
      'Kuasai matematika dasar yang mendeskripsikan pose robot di ruang Euclidean 2D dan 3D: vektor, cosinus arah, rotasi SO(2)/SO(3), dan rantai transformasi kaku SE(2)/SE(3).',
    estimatedHours: 14,
    badge: 'Foundations Track',
    icon: '📐',
    colorGradient: 'from-violet-500/20 via-purple-600/15 to-indigo-600/20',
    steps: [
      {
        stepNumber: 1,
        level: 1,
        moduleId: 'vectors-and-coordinate-geometry',
        titleEn: 'Vectors, Euclidean Norms & Unit Directions',
        titleId: 'Vektor, Norma Euclidean & Arah Satuan',
        descEn: 'Vector decomposition, Pythagorean magnitude, and Cartesian reference frames.',
        descId: 'Dekomposisi vektor, magnitudo Pythagoras, dan kerangka acuan Kartesius.',
        theoryHref: '/learn/mathematics/vectors-and-coordinate-geometry',
        labId: 'vector-explorer',
        labName: 'Vector Explorer Lab',
        keyEquation: '\\hat{\\mathbf{v}} = \\frac{\\mathbf{v}}{\\|\\mathbf{v}\\|}',
        prerequisites: ['Basic High School Algebra'],
      },
      {
        stepNumber: 2,
        level: 1,
        moduleId: 'dot-product-and-projection',
        titleEn: 'Dot Product, Orthogonality & Projection',
        titleId: 'Perkalian Titik, Ortogonalitas & Proyeksi',
        descEn: 'Compute cosine similarity and project points onto directional axes.',
        descId: 'Hitung kesamaan kosinus dan proyeksikan titik ke sumbu arah.',
        theoryHref: '/learn/mathematics/dot-product-and-projection',
        labId: 'dot-product',
        labName: 'Dot Product Lab',
        keyEquation: '\\mathbf{a} \\cdot \\mathbf{b} = \\|\\mathbf{a}\\|\\|\\mathbf{b}\\|\\cos\\theta',
        prerequisites: ['Vectors'],
      },
      {
        stepNumber: 2,
        level: 2,
        moduleId: '2d-rotation-matrices',
        titleEn: '2D Rotations & SO(2) Orthogonal Matrices',
        titleId: 'Rotasi 2D & Matriks Ortogonal SO(2)',
        descEn: 'Rotate points in 2D with orthogonal rotation matrices R(θ) where det(R) = 1.',
        descId: 'Putar titik di bidang 2D dengan matriks rotasi ortogonal R(θ) dengan det(R) = 1.',
        theoryHref: '/learn/geometry/2d-rotation-matrices',
        labId: 'transforms-2d',
        labName: '2D Transforms Lab',
        keyEquation: '\\mathbf{R}(\\theta) = \\begin{bmatrix} \\cos\\theta & -\\sin\\theta \\\\ \\sin\\theta & \\cos\\theta \\end{bmatrix}',
        prerequisites: ['Dot Product'],
      },
      {
        stepNumber: 3,
        level: 2,
        moduleId: 'coordinate-frames-and-transforms',
        titleEn: 'Rigid Body SE(2) Transformations',
        titleId: 'Transformasi Benda Kaku SE(2)',
        descEn: 'Represent simultaneous translation and rotation using 3x3 homogeneous matrices.',
        descId: 'Representasikan translasi dan rotasi simultan dengan matriks homogen 3x3.',
        theoryHref: '/learn/geometry/coordinate-frames-and-transforms',
        labId: 'transforms-2d',
        labName: 'Transform Sandbox',
        keyEquation: '\\mathbf{T} = \\begin{bmatrix} \\mathbf{R} & \\mathbf{t} \\\\ \\mathbf{0}^T & 1 \\end{bmatrix}',
        prerequisites: ['2D Rotations'],
      },
      {
        stepNumber: 4,
        level: 2,
        moduleId: 'transform-composition-and-chains',
        titleEn: 'Transform Composition & Matrix Non-Commutativity',
        titleId: 'Komposisi Transformasi & Sifat Non-Komutatif',
        descEn: 'Chain coordinate frames along kinematic links and understand why T1*T2 ≠ T2*T1.',
        descId: 'Rangkai kerangka koordinat di sepanjang rantai kinematik dan pahami sifat non-komutatif.',
        theoryHref: '/learn/geometry/transform-composition-and-chains',
        labId: 'transform-composition',
        labName: 'Transform Chaining Lab',
        keyEquation: '\\mathbf{T}_A^C = \\mathbf{T}_A^B \\mathbf{T}_B^C',
        prerequisites: ['SE(2) Transforms'],
      },
    ],
  },
  {
    id: 'sensor-estimation',
    slug: 'sensor-estimation',
    titleEn: 'Sensor Perception & State Estimation',
    titleId: 'Persepsi Sensor & Estimasi Status',
    subtitleEn: 'Uncertainty, Odometry Drift, LiDAR Raycasting & Bayesian Filtering',
    subtitleId: 'Ketidakpastian, Drift Odometri, Raycasting LiDAR & Filter Bayesian',
    descriptionEn:
      'Learn how robots perceive their surroundings in the presence of noise: Gaussian sensor models, dead reckoning drift accumulation, 360° laser raycasting, and recursive Bayesian prediction-correction filters.',
    descriptionId:
      'Pelajari bagaimana robot mempersepsikan lingkungan di bawah pengaruh derau: model Gaussian, akumulasi drift dead reckoning, raycasting laser 360°, dan filter prediksi-koreksi Bayesian.',
    estimatedHours: 16,
    badge: 'Estimation Track',
    icon: '📡',
    colorGradient: 'from-blue-500/20 via-cyan-600/15 to-teal-600/20',
    steps: [
      {
        stepNumber: 1,
        level: 5,
        moduleId: 'sensor-noise-and-uncertainty',
        titleEn: 'Gaussian Sensor Noise & Probability Density',
        titleId: 'Derau Sensor Gaussian & Kerapatan Probabilitas',
        descEn: 'Model electronic and thermal measurement noise with normal distributions N(μ, σ²).',
        descId: 'Modelkan derau pengukuran termal dan elektronik dengan distribusi normal N(μ, σ²).',
        theoryHref: '/learn/sensors/sensor-noise-and-uncertainty',
        labId: 'sensor-noise',
        labName: 'Sensor Noise Lab',
        keyEquation: 'p(z \\mid x) = \\frac{1}{\\sqrt{2\\pi\\sigma^2}} \\exp\\left(-\\frac{(z - x)^2}{2\\sigma^2}\\right)',
        prerequisites: ['Probability Foundations'],
      },
      {
        stepNumber: 2,
        level: 5,
        moduleId: 'wheel-odometry-and-drift',
        titleEn: 'Wheel Odometry & Dead Reckoning Drift',
        titleId: 'Odometri Roda & Akumulasi Galat Drift',
        descEn: 'Integrate wheel pulses and observe heading error divergence over time.',
        descId: 'Integrasikan pulsa roda dan amati divergensi galat orientasi robot.',
        theoryHref: '/learn/sensors/wheel-odometry-and-drift',
        labId: 'wheel-odometry',
        labName: 'Odometry Drift Lab',
        keyEquation: '\\Delta\\theta = \\frac{\\Delta s_R - \\Delta s_L}{L}',
        prerequisites: ['Sensor Noise'],
      },
      {
        stepNumber: 3,
        level: 5,
        moduleId: 'lidar-raycasting',
        titleEn: 'LiDAR Raycasting & Point Cloud Extraction',
        titleId: 'Raycasting LiDAR & Ekstraksi Point Cloud',
        descEn: 'Calculate Time-of-Flight distances and project laser rays into 2D Cartesian points.',
        descId: 'Hitung jarak Time-of-Flight dan proyeksikan sinar laser ke titik Kartesius 2D.',
        theoryHref: '/learn/sensors/lidar-raycasting',
        labId: 'lidar-raycast',
        labName: 'LiDAR Raycasting Lab',
        keyEquation: 'd = \\frac{c \\cdot \\Delta t}{2}',
        prerequisites: ['Coordinate Frames'],
      },
      {
        stepNumber: 4,
        level: 8,
        moduleId: 'bayes-filter-and-kalman',
        titleEn: '1D Recursive Bayesian & Kalman Filtering',
        titleId: 'Filter Bayesian & Kalman Rekursif 1D',
        descEn: 'Fuse motion predictions with noisy sensor updates to reduce state uncertainty.',
        descId: 'Gabungkan prediksi gerak dengan pembaruan sensor untuk meminimalkan ketidakpastian.',
        theoryHref: '/learn/estimation/bayes-filter-and-kalman',
        labId: 'bayesian-filter',
        labName: 'Bayesian Filter Lab',
        keyEquation: 'K_t = \\frac{\\sigma_{p}^2}{\\sigma_{p}^2 + \\sigma_{z}^2}',
        prerequisites: ['Sensor Noise', 'Wheel Odometry'],
      },
    ],
  },
  {
    id: 'motion-planning',
    slug: 'motion-planning',
    titleEn: 'Motion Planning & Trajectory Search',
    titleId: 'Perencanaan Gerak & Pencarian Trajektori',
    subtitleEn: 'C-Space, Discrete A*/Dijkstra & Randomized Sampling Planners',
    subtitleId: 'C-Space, Pencarian Diskrit A*/Dijkstra & Perencana Sampel Acak',
    descriptionEn:
      'Master path planning in complex environments: Minkowski sum obstacle inflation into Configuration Space (C-Space), heuristic graph search with A*, and continuous space sampling with RRT and RRT*.',
    descriptionId:
      'Kuasai perencanaan jalur di lingkungan kompleks: inflasi rintangan Minkowski ke Ruang Konfigurasi (C-Space), pencarian graf heuristik A*, dan sampling ruang kontinu dengan RRT dan RRT*.',
    estimatedHours: 16,
    badge: 'Planning Track',
    icon: '🗺️',
    colorGradient: 'from-fuchsia-500/20 via-pink-600/15 to-rose-600/20',
    steps: [
      {
        stepNumber: 1,
        level: 2,
        moduleId: 'configuration-space-and-minkowski',
        titleEn: 'Configuration Space & Minkowski Inflation',
        titleId: 'Ruang Konfigurasi & Inflasi Minkowski',
        descEn: 'Inflate geometric obstacles by robot radius to simplify collision checking.',
        descId: 'Perluas geometri rintangan sebesar radius robot untuk menyederhanakan uji tabrakan.',
        theoryHref: '/learn/geometry/configuration-space-and-minkowski',
        labId: 'cspace-inflation',
        labName: 'C-Space Inflation Lab',
        keyEquation: 'C_{\\text{obs}} = \\mathcal{O} \\oplus \\mathcal{B}_r',
        prerequisites: ['Vector Geometry'],
      },
      {
        stepNumber: 2,
        level: 6,
        moduleId: 'a-star',
        titleEn: 'A* Heuristic Graph Search',
        titleId: 'Pencarian Graf Heuristik A*',
        descEn: 'Evaluate shortest paths on 2D grids using f(n) = g(n) + h(n) with Euclidean distance heuristics.',
        descId: 'Evaluasi jalur terpendek pada grid 2D menggunakan f(n) = g(n) + h(n) dengan heuristik Euclidean.',
        theoryHref: '/learn/planning/a-star',
        labId: 'a-star-planning',
        labName: 'A* Path Search Lab',
        keyEquation: 'f(n) = g(n) + h(n)',
        prerequisites: ['C-Space Inflation'],
      },
      {
        stepNumber: 3,
        level: 6,
        moduleId: 'astar-vs-dijkstra-search',
        titleEn: 'A* vs Dijkstra Search Strategy Comparison',
        titleId: 'Komparasi Strategi Pencarian A* vs Dijkstra',
        descEn: 'Compare uniform blind wavefronts with goal-directed heuristic search cones.',
        descId: 'Bandingkan gelombang buta seragam Dijkstra vs kerucut pencarian terarah A*.',
        theoryHref: '/learn/planning/astar-vs-dijkstra-search',
        labId: 'astar-dijkstra',
        labName: 'A* vs Dijkstra Lab',
        keyEquation: 'h_{\\text{Euclidean}}(n) = \\sqrt{(x_n - x_g)^2 + (y_n - y_g)^2}',
        prerequisites: ['A* Search'],
      },
      {
        stepNumber: 4,
        level: 6,
        moduleId: 'rrt-sampling-planner',
        titleEn: 'RRT & RRT* Randomized Sampling Planners',
        titleId: 'Perencana Sampel Acak RRT & RRT*',
        descEn: 'Grow random exploration trees in continuous space with asymptotic rewiring optimality.',
        descId: 'Tumbuhkan pohon eksplorasi acak di ruang kontinu dengan optimalitas asimtotik rewiring.',
        theoryHref: '/learn/planning/rrt-sampling-planner',
        labId: 'rrt-sampling',
        labName: 'RRT Sampling Lab',
        keyEquation: 'q_{\\text{new}} = q_{\\text{near}} + \\Delta q \\frac{q_{\\text{rand}} - q_{\\text{near}}}{\\|q_{\\text{rand}} - q_{\\text{near}}\\|}',
        prerequisites: ['C-Space Inflation'],
      },
    ],
  },
];
