export interface CurriculumLevel {
  level: number;
  id: string;
  tier: 'Foundations' | 'Core Autonomy' | 'Spatial Intelligence' | 'Advanced Embodiments';
  titleEn: string;
  titleId: string;
  descriptionEn: string;
  descriptionId: string;
  badge: string;
  estimatedHours: number;
  prerequisites: string[];
  modules: {
    id: string;
    titleEn: string;
    titleId: string;
    topicsCount: number;
    href: string;
    isInteractive: boolean;
  }[];
}

export const MASTER_CURRICULUM_LEVELS: CurriculumLevel[] = [
  // TIER 1: FOUNDATIONS (LEVELS 0 - 4)
  {
    level: 0,
    id: 'orientation',
    tier: 'Foundations',
    titleEn: 'Level 0 — Robotics Orientation',
    titleId: 'Level 0 — Orientasi Robotika',
    descriptionEn: 'Introduction to cyber-physical autonomy, Sense-Plan-Act loops, hardware/software anatomy, and robot taxonomy.',
    descriptionId: 'Pengantar sistem siber-fisik otonom, siklus Sense-Plan-Act, anatomi perangkat keras/lunak, dan klasifikasi robot.',
    badge: 'Beginner Friendly',
    estimatedHours: 2,
    prerequisites: ['None'],
    modules: [
      {
        id: 'intro-to-robotics',
        titleEn: 'Introduction to Autonomous Robotics & Classifications',
        titleId: 'Pengantar Robotika Otonom & Klasifikasinya',
        topicsCount: 8,
        href: '/learn/fundamentals/intro-to-robotics',
        isInteractive: true,
      },
    ],
  },
  {
    level: 1,
    id: 'mathematics',
    tier: 'Foundations',
    titleEn: 'Level 1 — Mathematical Foundations',
    titleId: 'Level 1 — Fondasi Matematika',
    descriptionEn: 'Scalars, Vectors, Matrices in SE(2)/SO(3), Euler Angles, Quaternions, Probability, and Least Squares Optimization.',
    descriptionId: 'Skalar, Vektor, Matriks SE(2)/SO(3), Sudut Euler, Kuaternion, Probabilitas, dan Optimasi Kuadrat Terkecil.',
    badge: 'Core Prerequisite',
    estimatedHours: 6,
    prerequisites: ['Level 0'],
    modules: [
      {
        id: 'mathematical-foundations',
        titleEn: 'Mathematical & Geometric Foundations for Robotics',
        titleId: 'Fundamental Matematika & Geometri untuk Robotika',
        topicsCount: 6,
        href: '/learn/mathematics/mathematical-foundations',
        isInteractive: true,
      },
      {
        id: 'vectors-and-coordinate-geometry',
        titleEn: 'Vectors & Euclidean Coordinate Geometry (M01)',
        titleId: 'Vektor & Geometri Koordinat Euclidean (M01)',
        topicsCount: 6,
        href: '/learn/mathematics/vectors-and-coordinate-geometry',
        isInteractive: true,
      },
      {
        id: 'dot-product-and-projection',
        titleEn: 'Dot Product, Orthogonality & Projection (M02)',
        titleId: 'Dot Product, Ortogonalitas & Proyeksi (M02)',
        topicsCount: 6,
        href: '/learn/mathematics/dot-product-and-projection',
        isInteractive: true,
      },
    ],
  },
  {
    level: 2,
    id: 'geometry',
    tier: 'Foundations',
    titleEn: 'Level 2 — Geometry & Transformations',
    titleId: 'Level 2 — Geometri & Transformasi',
    descriptionEn: 'World, Robot, and Sensor Frames. 2D/3D Homogeneous Transformation Matrices, Rotation Composition, and Frame Chains.',
    descriptionId: 'Kerangka Acuan Dunia, Robot, dan Sensor. Matriks Transformasi Homogen 2D/3D, Komposisi Rotasi, dan Rantai Kerangka.',
    badge: 'Spatial Math',
    estimatedHours: 5,
    prerequisites: ['Level 1'],
    modules: [
      {
        id: '2d-geometry',
        titleEn: '2D Planar Geometry & Homogeneous Transforms SE(2)',
        titleId: 'Geometri Planar 2D & Transformasi Homogen SE(2)',
        topicsCount: 6,
        href: '/learn/geometry/2d-geometry',
        isInteractive: true,
      },
      {
        id: '2d-rotation-matrices',
        titleEn: '2D Spatial Rotation & SO(2) Matrices (M03)',
        titleId: 'Rotasi Spasial 2D & Matriks SO(2) (M03)',
        topicsCount: 6,
        href: '/learn/geometry/2d-rotation-matrices',
        isInteractive: true,
      },
      {
        id: 'coordinate-frames-and-transforms',
        titleEn: 'Coordinate Frames, SE(2) & Frame Trees (M04)',
        titleId: 'Kerangka Koordinat, SE(2) & Pohon Kerangka (M04)',
        topicsCount: 6,
        href: '/learn/geometry/coordinate-frames-and-transforms',
        isInteractive: true,
      },
      {
        id: '3d-geometry',
        titleEn: '3D Spatial Geometry & SO(3) Rotations',
        titleId: 'Geometri Spasial 3D & Rotasi SO(3)',
        topicsCount: 6,
        href: '/learn/geometry/3d-geometry',
        isInteractive: true,
      },
      {
        id: 'configuration-space-and-minkowski',
        titleEn: 'Configuration Space & Minkowski Obstacle Inflation',
        titleId: 'Ruang Konfigurasi & Inflasi Rintangan Minkowski',
        topicsCount: 6,
        href: '/learn/geometry/configuration-space-and-minkowski',
        isInteractive: true,
      },
    ],
  },
  {
    level: 3,
    id: 'kinematics',
    tier: 'Foundations',
    titleEn: 'Level 3 — Robot Kinematics',
    titleId: 'Level 3 — Kinematika Robot',
    descriptionEn: 'Differential-drive unicycle models, Instantaneous Center of Curvature (ICC), Pfaffian non-holonomic constraints, and Forward/Inverse Kinematics.',
    descriptionId: 'Model unicycle roda diferensial, Pusat Kurvatur Seketika (ICC), kendala non-holonomik Pfaffian, dan Kinematika Maju/Invers.',
    badge: 'Mechanical Modeling',
    estimatedHours: 5,
    prerequisites: ['Level 2'],
    modules: [
      {
        id: 'velocity-kinematics-2d',
        titleEn: '2D Velocity Kinematics & Unicycle Models',
        titleId: 'Kinematika Kecepatan 2D & Model Unicycle',
        topicsCount: 6,
        href: '/learn/kinematics/velocity-kinematics-2d',
        isInteractive: true,
      },
    ],
  },
  {
    level: 4,
    id: 'motion-constraints',
    tier: 'Foundations',
    titleEn: 'Level 4 — Motion & Constraints',
    titleId: 'Level 4 — Gerak & Kendala Kinematik',
    descriptionEn: 'Spatial twists in se(3), skew-symmetric operators, Geometric Manipulator Jacobians, singularities, and velocity ellipsoids.',
    descriptionId: 'Spatial twist pada se(3), operator skew-symmetric, Jacobian Geometris Manipulator, singularitas, dan elipsoid kecepatan.',
    badge: 'Differential Geometry',
    estimatedHours: 6,
    prerequisites: ['Level 3'],
    modules: [
      {
        id: 'velocity-kinematics-3d',
        titleEn: '3D Velocity Kinematics & Geometric Jacobians',
        titleId: 'Kinematika Kecepatan 3D & Jacobian Geometris',
        topicsCount: 6,
        href: '/learn/kinematics/velocity-kinematics-2d',
        isInteractive: true,
      },
    ],
  },

  // TIER 2: CORE AUTONOMY (LEVELS 5 - 8)
  {
    level: 5,
    id: 'sensors-perception',
    tier: 'Core Autonomy',
    titleEn: 'Level 5 — Sensors & Perception',
    titleId: 'Level 5 — Sensor & Persepsi',
    descriptionEn: 'Optical encoders, Inertial Measurement Units (IMU), 2D/3D LiDAR raycasting, depth cameras, and Gaussian measurement noise models.',
    descriptionId: 'Enkoder optik, Unit Pengukuran Inersia (IMU), raycasting LiDAR 2D/3D, kamera kedalaman, dan model derau Gaussian.',
    badge: 'Hardware Perception',
    estimatedHours: 5,
    prerequisites: ['Level 1', 'Level 2'],
    modules: [
      {
        id: 'sensor-fundamentals',
        titleEn: 'Sensor Fundamentals & Gaussian Noise Models',
        titleId: 'Fundamental Sensor & Model Derau Gaussian',
        topicsCount: 6,
        href: '/learn/sensors/sensor-fundamentals',
        isInteractive: true,
      },
      {
        id: 'wheel-odometry-and-drift',
        titleEn: 'Wheel Odometry & Systematic Dead Reckoning Drift',
        titleId: 'Odometri Roda & Akumulasi Galat Drift',
        topicsCount: 6,
        href: '/learn/sensors/wheel-odometry-and-drift',
        isInteractive: true,
      },
    ],
  },
  {
    level: 6,
    id: 'algorithms-planning',
    tier: 'Core Autonomy',
    titleEn: 'Level 6 — Algorithms & Planning',
    titleId: 'Level 6 — Algoritma & Perencanaan Jalur',
    descriptionEn: 'Dijkstra, A* Heuristic Search, Configuration Space (C-Space) expansion, RRT, RRT*, and Quintic Polynomial Splines.',
    descriptionId: 'Dijkstra, Pencarian Heuristik A*, ekspansi Ruang Konfigurasi (C-Space), RRT, RRT*, dan Spline Polinomial Kuintik.',
    badge: 'Navigation Planning',
    estimatedHours: 7,
    prerequisites: ['Level 2', 'Level 4'],
    modules: [
      {
        id: 'a-star',
        titleEn: 'A* Grid Search & Admissible Heuristics',
        titleId: 'Pencarian Grid A* & Heuristik Admisibel',
        topicsCount: 6,
        href: '/learn/planning/a-star',
        isInteractive: true,
      },
      {
        id: 'rrt-and-rrt-star',
        titleEn: 'Sampling-Based Planning: RRT & RRT*',
        titleId: 'Perencanaan Berbasis Sampel: RRT & RRT*',
        topicsCount: 6,
        href: '/learn/planning/rrt-and-rrt-star',
        isInteractive: true,
      },
    ],
  },
  {
    level: 7,
    id: 'dynamics-control',
    tier: 'Core Autonomy',
    titleEn: 'Level 7 — Dynamics & Control',
    titleId: 'Level 7 — Dinamika & Kendali',
    descriptionEn: 'Pure Pursuit lookahead geometry, Stanley cross-track non-linear feedback, PID controllers, and Newton-Euler / Euler-Lagrange dynamics.',
    descriptionId: 'Kemudi geometris Pure Pursuit, umpan balik lateral Stanley, kontroler PID, dan dinamika Newton-Euler / Euler-Lagrange.',
    badge: 'Motion Control',
    estimatedHours: 6,
    prerequisites: ['Level 3', 'Level 6'],
    modules: [
      {
        id: 'pure-pursuit-and-stanley',
        titleEn: 'Pure Pursuit & Stanley Path Tracking',
        titleId: 'Pelacakan Jalur Pure Pursuit & Stanley',
        topicsCount: 6,
        href: '/learn/control/pure-pursuit-and-stanley',
        isInteractive: true,
      },
      {
        id: 'pid-and-lqr-control',
        titleEn: 'PID Feedback Control & Transient Response',
        titleId: 'Kendali Umpan Balik PID & Respon Transien',
        topicsCount: 6,
        href: '/learn/control/pid-and-lqr-control',
        isInteractive: true,
      },
    ],
  },
  {
    level: 8,
    id: 'state-estimation',
    tier: 'Core Autonomy',
    titleEn: 'Level 8 — State Estimation',
    titleId: 'Level 8 — Estimasi Status & Lokalisasi',
    descriptionEn: 'Recursive Bayesian Filtering, Chapman-Kolmogorov motion prediction, Monte Carlo Localization (MCL) Particle Filters, and EKF.',
    descriptionId: 'Filter Bayesian Rekursif, prediksi gerak Chapman-Kolmogorov, Filter Partikel Monte Carlo (MCL), dan EKF.',
    badge: 'State Estimation',
    estimatedHours: 6,
    prerequisites: ['Level 5', 'Level 7'],
    modules: [
      {
        id: 'bayes-filter-and-kalman',
        titleEn: '1D Bayesian Filtering & Kalman Prediction-Correction',
        titleId: 'Filter Bayesian 1D & Prediksi-Koreksi Kalman',
        topicsCount: 6,
        href: '/learn/estimation/bayes-filter-and-kalman',
        isInteractive: true,
      },
      {
        id: 'mcl-particle-filter',
        titleEn: 'Monte Carlo Localization Particle Filters',
        titleId: 'Filter Partikel Monte Carlo Localization',
        topicsCount: 5,
        href: '/learn/estimation/mcl-particle-filter',
        isInteractive: true,
      },
    ],
  },

  // TIER 3: SPATIAL INTELLIGENCE & SLAM (LEVELS 9 - 12)
  {
    level: 9,
    id: 'mapping',
    tier: 'Spatial Intelligence',
    titleEn: 'Level 9 — Mapping & Spatial Occupancy',
    titleId: 'Level 9 — Pemetaan & Okupansi Spasial',
    descriptionEn: 'Log-Odds Bayesian Occupancy Grid Mapping, Euclidean Distance Transforms (EDT), costmap inflation layers, and topological maps.',
    descriptionId: 'Pemetaan Grid Okupansi Log-Odds Bayesian, Euclidean Distance Transform (EDT), lapisan inflasi costmap, dan peta topologis.',
    badge: 'Spatial Modeling',
    estimatedHours: 5,
    prerequisites: ['Level 5', 'Level 8'],
    modules: [
      {
        id: 'occupancy-grid-mapping',
        titleEn: 'Log-Odds Occupancy Grid Mapping',
        titleId: 'Pemetaan Grid Okupansi Log-Odds',
        topicsCount: 5,
        href: '/learn/perception/occupancy-grid-mapping',
        isInteractive: true,
      },
    ],
  },
  {
    level: 10,
    id: 'computer-vision',
    tier: 'Spatial Intelligence',
    titleEn: 'Level 10 — Computer Vision & Perception',
    titleId: 'Level 10 — Visi Komputer & Persepsi',
    descriptionEn: 'Pinhole camera models, intrinsic/extrinsic calibration, epipolar geometry, feature matching (ORB/SIFT), and optical flow.',
    descriptionId: 'Model kamera pinhole, kalibrasi intrinsik/ekstrinsik, geometri epipolar, pencocokan fitur (ORB/SIFT), dan optical flow.',
    badge: 'Vision Perception',
    estimatedHours: 6,
    prerequisites: ['Level 2', 'Level 5'],
    modules: [
      {
        id: 'camera-calibration',
        titleEn: 'Pinhole Camera Geometry & Calibration',
        titleId: 'Geometri Kamera Pinhole & Kalibrasi',
        topicsCount: 5,
        href: '/learn/perception/occupancy-grid-mapping',
        isInteractive: true,
      },
    ],
  },
  {
    level: 11,
    id: 'slam',
    tier: 'Spatial Intelligence',
    titleEn: 'Level 11 — Simultaneous Localization & Mapping (SLAM)',
    titleId: 'Level 11 — Lokalisasi & Pemetaan Simultan (SLAM)',
    descriptionEn: 'Iterative Closest Point (ICP) scan matching, closed-form SVD rotation, pose-graph optimization, and loop closure detection.',
    descriptionId: 'Pencocokan pindaian Iterative Closest Point (ICP), rotasi analitik SVD, optimasi pose-graph, dan deteksi loop closure.',
    badge: 'Full Spatial Autonomy',
    estimatedHours: 7,
    prerequisites: ['Level 8', 'Level 9'],
    modules: [
      {
        id: 'icp-scan-matching',
        titleEn: 'Iterative Closest Point (ICP) Scan Matching',
        titleId: 'Pencocokan Pindaian Iterative Closest Point (ICP)',
        topicsCount: 5,
        href: '/learn/advanced/icp-scan-matching',
        isInteractive: true,
      },
    ],
  },
  {
    level: 12,
    id: 'autonomous-systems',
    tier: 'Spatial Intelligence',
    titleEn: 'Level 12 — Autonomous Systems Architecture',
    titleId: 'Level 12 — Arsitektur Sistem Otonom',
    descriptionEn: 'Hierarchical state machines, Behavior Trees (BT), mission planners, fault monitoring, and safety-critical watchdog systems.',
    descriptionId: 'Mesin status hierarkis, Behavior Trees (BT), perencana misi, pemantau kegagalan, dan sistem keselamatan kritis.',
    badge: 'System Architecture',
    estimatedHours: 5,
    prerequisites: ['Level 11'],
    modules: [
      {
        id: 'behavior-trees',
        titleEn: 'Behavior Trees & Autonomy Executive',
        titleId: 'Behavior Trees & Eksekutif Otonomi',
        topicsCount: 4,
        href: '/learn/fundamentals/intro-to-robotics',
        isInteractive: true,
      },
    ],
  },

  // TIER 4: ADVANCED EMBODIMENTS & SPECIALIZATIONS (LEVELS 13 - 20)
  {
    level: 13,
    id: 'robotics-software',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 13 — Robotics Software & Simulation',
    titleId: 'Level 13 — Perangkat Lunak Robotika & Simulasi',
    descriptionEn: 'ROS 2 DDS middleware, nodes, topics, services, actions, URDF robot description models, and Gazebo physics simulation.',
    descriptionId: 'Middleware ROS 2 DDS, node, topik, layanan, aksi, model deskripsi robot URDF, dan simulasi fisik Gazebo.',
    badge: 'Software Engineering',
    estimatedHours: 6,
    prerequisites: ['Level 3', 'Level 12'],
    modules: [
      {
        id: 'ros2-architecture',
        titleEn: 'ROS 2 Computation Graph & URDF Models',
        titleId: 'Graf Komputasi ROS 2 & Model URDF',
        topicsCount: 5,
        href: '/learn/fundamentals/intro-to-robotics',
        isInteractive: true,
      },
    ],
  },
  {
    level: 14,
    id: 'manipulation',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 14 — Manipulation Robotics',
    titleId: 'Level 14 — Robotika Manipulasi',
    descriptionEn: 'Forward/Inverse Kinematics (IK), Denavit-Hartenberg (DH) parameters, analytical & numerical IK, grasp planning, and MoveIt pipeline.',
    descriptionId: 'Kinematika Maju/Invers (IK), parameter Denavit-Hartenberg (DH), IK analitik & numerik, perencanaan genggaman, dan MoveIt.',
    badge: 'Articulated Arms',
    estimatedHours: 7,
    prerequisites: ['Level 4', 'Level 7'],
    modules: [
      {
        id: 'manipulator-kinematics',
        titleEn: '6-DOF Manipulator Forward & Inverse Kinematics',
        titleId: 'Kinematika Maju & Invers Manipulator 6-DOF',
        topicsCount: 6,
        href: '/learn/manipulation/forward-inverse-kinematics',
        isInteractive: true,
      },
    ],
  },
  {
    level: 15,
    id: 'mobile-robotics',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 15 — Mobile Robotics',
    titleId: 'Level 15 — Robotika Bergerak',
    descriptionEn: 'Wheeled rovers, omnidirectional mecanum chassis, Ackermann car-like steering kinematics, and slip modeling.',
    descriptionId: 'Rover beroda, sasis roda omni mecanum, kinematika kemudi Ackermann, dan pemodelan slip traksi.',
    badge: 'Wheeled Autonomy',
    estimatedHours: 6,
    prerequisites: ['Level 3', 'Level 7'],
    modules: [
      {
        id: 'mobile-kinematics-advanced',
        titleEn: 'Ackermann & Omnidirectional Mobile Chassis',
        titleId: 'Sasis Bergerak Ackermann & Omnidireksional',
        topicsCount: 5,
        href: '/learn/kinematics/velocity-kinematics-2d',
        isInteractive: true,
      },
    ],
  },
  {
    level: 16,
    id: 'aerial-robotics',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 16 — Aerial Robotics',
    titleId: 'Level 16 — Robotika Udara',
    descriptionEn: '6-DOF quadrotor flight dynamics, SE(3) geometric attitude control, differential flatness, and minimum-snap trajectory generation.',
    descriptionId: 'Dinamika penerbangan quadrotor 6-DOF, kendali sikap geometris SE(3), diferensial flatness, dan pembuatan trajektori minimum-snap.',
    badge: 'Flight Dynamics',
    estimatedHours: 7,
    prerequisites: ['Level 2', 'Level 7'],
    modules: [
      {
        id: 'quadrotor-dynamics',
        titleEn: 'Quadrotor Flight Dynamics & Minimum-Snap',
        titleId: 'Dinamika Terbang Quadrotor & Minimum-Snap',
        topicsCount: 5,
        href: '/learn/geometry/3d-geometry',
        isInteractive: true,
      },
    ],
  },
  {
    level: 17,
    id: 'marine-robotics',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 17 — Marine Robotics',
    titleId: 'Level 17 — Robotika Bawah Air & Laut',
    descriptionEn: 'Hydrodynamics, added mass, buoyant stability, thruster allocation matrix, and acoustic underwater localization.',
    descriptionId: 'Hidrodinamika, added mass, stabilitas daya apung, matriks alokasi pendorong, dan lokalisasi akustik bawah air.',
    badge: 'Subsea Robotics',
    estimatedHours: 6,
    prerequisites: ['Level 2', 'Level 7'],
    modules: [
      {
        id: 'marine-hydrodynamics',
        titleEn: 'Underwater Hydrodynamics & Thruster Mixing',
        titleId: 'Hidrodinamika Bawah Air & Alokasi Pendorong',
        topicsCount: 5,
        href: '/robots',
        isInteractive: true,
      },
    ],
  },
  {
    level: 18,
    id: 'legged-humanoid',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 18 — Legged & Humanoid Robotics',
    titleId: 'Level 18 — Robotika Berkaki & Humanoid',
    descriptionEn: 'Zero Moment Point (ZMP), Linear Inverted Pendulum Model (LIPM), gait sequencing (trot, bound, gallop), and whole-body control (WBC).',
    descriptionId: 'Zero Moment Point (ZMP), Linear Inverted Pendulum Model (LIPM), sekuens gaya berjalan (trot, bound, gallop), dan Whole-Body Control.',
    badge: 'Legged Locomotion',
    estimatedHours: 7,
    prerequisites: ['Level 4', 'Level 7'],
    modules: [
      {
        id: 'legged-locomotion',
        titleEn: 'Inverted Pendulum Dynamics & Gait Planning',
        titleId: 'Dinamika Pendulum Terbalik & Perencanaan Gait',
        topicsCount: 5,
        href: '/robots',
        isInteractive: true,
      },
    ],
  },
  {
    level: 19,
    id: 'advanced-math',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 19 — Advanced Robotics Mathematics',
    titleId: 'Level 19 — Matematika Lanjutan untuk Robotika',
    descriptionEn: 'Matrix Lie groups SO(3)/SE(3), Lie algebras so(3)/se(3), exponential map, adjoint representations, and factor graph optimization.',
    descriptionId: 'Grup Lie matriks SO(3)/SE(3), aljabar Lie so(3)/se(3), pemetaan eksponensial, representasi adjoint, dan optimasi graf faktor.',
    badge: 'Lie Groups & Manifolds',
    estimatedHours: 8,
    prerequisites: ['Level 1', 'Level 4', 'Level 10'],
    modules: [
      {
        id: 'lie-theory-robotics',
        titleEn: 'Lie Groups, Lie Algebras & Manifold Optimization',
        titleId: 'Grup Lie, Aljabar Lie & Optimasi Manifold',
        topicsCount: 6,
        href: '/learn/geometry/3d-geometry',
        isInteractive: true,
      },
    ],
  },
  {
    level: 20,
    id: 'research-emerging',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 20 — Robotics Research & Emerging Topics',
    titleId: 'Level 20 — Riset Robotika & Topik Terdepan',
    descriptionEn: 'Soft robotics continuum mechanics, neural radiance fields (NeRF/3DGS) for robotics, micro-robotics, and open benchmark problems.',
    descriptionId: 'Mekanika kontinuum soft robotics, Neural Radiance Fields (NeRF/3DGS), mikro-robotika, dan tolok ukur riset terbuka.',
    badge: 'Frontier Research',
    estimatedHours: 8,
    prerequisites: ['Level 10', 'Level 18', 'Level 19'],
    modules: [
      {
        id: 'frontier-robotics',
        titleEn: 'Frontier Robotics: NeRF SLAM & Soft Continuum',
        titleId: 'Robotika Terdepan: NeRF SLAM & Kontinuum Fleksibel',
        topicsCount: 5,
        href: '/learn/advanced/icp-scan-matching',
        isInteractive: true,
      },
    ],
  },
];
