export interface CurriculumLevel {
  level: number;
  id: string;
  tier: 'Foundations' | 'Core Autonomy' | 'Spatial Intelligence' | 'Advanced Embodiments';
  titleEn: string;
  titleId: string;
  descriptionEn: string;
  descriptionId: string;
  badge: string;
  estimatedHours: number;
  prerequisites: string[];
  modules: {
    id: string;
    titleEn: string;
    titleId: string;
    topicsCount: number;
    href: string;
    isInteractive: boolean;
  }[];
}

export const MASTER_CURRICULUM_LEVELS: CurriculumLevel[] = [
  // TIER 1: FOUNDATIONS (LEVELS 0 - 4)
  {
    level: 0,
    id: 'orientation',
    tier: 'Foundations',
    titleEn: 'Level 0 — Robotics Orientation & Embodiments',
    titleId: 'Level 0 — Orientasi Robotika & Embodimen',
    descriptionEn: 'Introduction to cyber-physical autonomy, Sense-Plan-Act loops, hardware/software anatomy, and physical robot embodiments.',
    descriptionId: 'Pengantar sistem siber-fisik otonom, siklus Sense-Plan-Act, anatomi perangkat keras/lunak, dan berbagai platform robot fisik.',
    badge: 'Beginner Friendly',
    estimatedHours: 4,
    prerequisites: ['None'],
    modules: [
      {
        id: 'intro-to-robotics',
        titleEn: 'Introduction to Autonomous Robotics & Classifications',
        titleId: 'Pengantar Robotika Otonom & Klasifikasinya',
        topicsCount: 8,
        href: '/learn/fundamentals/intro-to-robotics',
        isInteractive: true,
      },
      {
        id: 'aerial-drone-principles',
        titleEn: 'Aerial Robotics: Multirotor Flight Dynamics & 6-DOF Thrust',
        titleId: 'Robotika Udara: Dinamika Multirotor & Kendali Dorong 6-DOF',
        topicsCount: 6,
        href: '/learn/fundamentals/aerial-drone-principles',
        isInteractive: true,
      },
      {
        id: 'marine-robotics-fundamentals',
        titleEn: 'Marine Robotics: Hydrodynamics, Buoyancy & Fossen Equations',
        titleId: 'Robotika Laut: Hidrodinamika, Gaya Apung & Persamaan Fossen',
        topicsCount: 6,
        href: '/learn/fundamentals/marine-robotics-fundamentals',
        isInteractive: true,
      },
      {
        id: 'legged-robotics-fundamentals',
        titleEn: 'Legged Robotics: Zero Moment Point (ZMP) & LIPM Locomotion',
        titleId: 'Robotika Berkaki: Zero Moment Point (ZMP) & Lokomosi LIPM',
        topicsCount: 6,
        href: '/learn/fundamentals/legged-robotics-fundamentals',
        isInteractive: true,
      },
    ],
  },
  {
    level: 1,
    id: 'mathematics',
    tier: 'Foundations',
    titleEn: 'Level 1 — Mathematical Foundations',
    titleId: 'Level 1 — Fondasi Matematika',
    descriptionEn: 'Scalars, Vectors, Norms, Dot/Cross Products, Skew-Symmetric Matrices, Numerical Integration, and Probability Theory.',
    descriptionId: 'Skalar, Vektor, Norma, Perkalian Titik/Silang, Matriks Skew-Symmetric, Integrasi Numerik, dan Teori Probabilitas.',
    badge: 'Core Prerequisite',
    estimatedHours: 6,
    prerequisites: ['Level 0'],
    modules: [
      {
        id: 'mathematical-foundations',
        titleEn: 'Mathematical & Geometric Foundations for Robotics',
        titleId: 'Fundamental Matematika & Geometri untuk Robotika',
        topicsCount: 8,
        href: '/learn/mathematics/mathematical-foundations',
        isInteractive: true,
      },
      {
        id: 'vectors-and-coordinate-geometry',
        titleEn: 'Vectors & Euclidean Coordinate Geometry (M01)',
        titleId: 'Vektor & Geometri Koordinat Euclidean (M01)',
        topicsCount: 6,
        href: '/learn/mathematics/vectors-and-coordinate-geometry',
        isInteractive: true,
      },
      {
        id: 'dot-product-and-projection',
        titleEn: 'Dot Product, Orthogonality & Projection (M02)',
        titleId: 'Dot Product, Ortogonalitas & Proyeksi (M02)',
        topicsCount: 6,
        href: '/learn/mathematics/dot-product-and-projection',
        isInteractive: true,
      },
      {
        id: 'probability-for-robotics',
        titleEn: 'Probability & Bayesian Reasoning (M10)',
        titleId: 'Teori Probabilitas & Penalaran Bayesian (M10)',
        topicsCount: 6,
        href: '/learn/mathematics/probability-for-robotics',
        isInteractive: true,
      },
      {
        id: 'numerical-stability-euler-vs-rk4',
        titleEn: 'Numerical Stability & Integration: Euler vs RK4 (M29)',
        titleId: 'Stabilitas Numerik & Integrasi: Euler vs RK4 (M29)',
        topicsCount: 6,
        href: '/learn/mathematics/numerical-stability-euler-vs-rk4',
        isInteractive: true,
      },
    ],
  },
  {
    level: 2,
    id: 'geometry',
    tier: 'Foundations',
    titleEn: 'Level 2 — Geometry & Transformations',
    titleId: 'Level 2 — Geometri & Transformasi',
    descriptionEn: 'World, Robot, and Sensor Frames. 2D/3D Homogeneous Transformation Matrices, Rotation Composition, Frame Chains, and Lie Groups.',
    descriptionId: 'Kerangka Acuan Dunia, Robot, dan Sensor. Matriks Transformasi Homogen 2D/3D, Komposisi Rotasi, Rantai Kerangka, dan Grup Lie.',
    badge: 'Spatial Math',
    estimatedHours: 6,
    prerequisites: ['Level 1'],
    modules: [
      {
        id: '2d-geometry',
        titleEn: '2D Planar Geometry & Homogeneous Transforms SE(2)',
        titleId: 'Geometri Planar 2D & Transformasi Homogen SE(2)',
        topicsCount: 6,
        href: '/learn/geometry/2d-geometry',
        isInteractive: true,
      },
      {
        id: '2d-rotation-matrices',
        titleEn: '2D Spatial Rotation & SO(2) Matrices (M03)',
        titleId: 'Rotasi Spasial 2D & Matriks SO(2) (M03)',
        topicsCount: 6,
        href: '/learn/geometry/2d-rotation-matrices',
        isInteractive: true,
      },
      {
        id: 'coordinate-frames-and-transforms',
        titleEn: 'Coordinate Frames, SE(2) & Frame Trees (M04)',
        titleId: 'Kerangka Koordinat, SE(2) & Pohon Kerangka (M04)',
        topicsCount: 6,
        href: '/learn/geometry/coordinate-frames-and-transforms',
        isInteractive: true,
      },
      {
        id: 'transform-composition-and-chains',
        titleEn: 'Transform Composition & Kinematic Chains (M05)',
        titleId: 'Komposisi Transformasi & Rantai Kinematik (M05)',
        topicsCount: 6,
        href: '/learn/geometry/transform-composition-and-chains',
        isInteractive: true,
      },
      {
        id: '3d-geometry',
        titleEn: '3D Spatial Geometry & SO(3) Rotations',
        titleId: 'Geometri Spasial 3D & Rotasi SO(3)',
        topicsCount: 6,
        href: '/learn/geometry/3d-geometry',
        isInteractive: true,
      },
      {
        id: 'lie-groups-and-lie-algebras',
        titleEn: 'Matrix Lie Groups SO(3)/SE(3) & Lie Algebras so(3)/se(3)',
        titleId: 'Grup Lie Matriks SO(3)/SE(3) & Aljabar Lie so(3)/se(3)',
        topicsCount: 6,
        href: '/learn/geometry/lie-groups-and-lie-algebras',
        isInteractive: true,
      },
      {
        id: 'configuration-space-and-minkowski',
        titleEn: 'Configuration Space & Minkowski Obstacle Inflation (M16)',
        titleId: 'Ruang Konfigurasi & Inflasi Rintangan Minkowski (M16)',
        topicsCount: 6,
        href: '/learn/geometry/configuration-space-and-minkowski',
        isInteractive: true,
      },
    ],
  },
  {
    level: 3,
    id: 'kinematics',
    tier: 'Foundations',
    titleEn: 'Level 3 — Robot Kinematics',
    titleId: 'Level 3 — Kinematika Robot',
    descriptionEn: 'Differential-drive unicycle models, Instantaneous Center of Curvature (ICC), and Pfaffian non-holonomic constraints.',
    descriptionId: 'Model unicycle roda diferensial, Pusat Kurvatur Seketika (ICC), dan kendala non-holonomik Pfaffian.',
    badge: 'Mechanical Modeling',
    estimatedHours: 5,
    prerequisites: ['Level 2'],
    modules: [
      {
        id: 'velocity-kinematics-2d',
        titleEn: '2D Velocity Kinematics & Unicycle Models',
        titleId: 'Kinematika Kecepatan 2D & Model Unicycle',
        topicsCount: 6,
        href: '/learn/kinematics/velocity-kinematics-2d',
        isInteractive: true,
      },
      {
        id: 'differential-drive-kinematics',
        titleEn: 'Differential Drive Forward Kinematics & ICC (M06)',
        titleId: 'Kinematika Maju Roda Diferensial & ICC (M06)',
        topicsCount: 6,
        href: '/learn/kinematics/differential-drive-kinematics',
        isInteractive: true,
      },
      {
        id: 'non-holonomic-constraints',
        titleEn: 'Non-Holonomic Constraints & Pfaffian Forms (M07)',
        titleId: 'Kendala Non-Holonomik & Bentuk Pfaffian (M07)',
        topicsCount: 6,
        href: '/learn/kinematics/non-holonomic-constraints',
        isInteractive: true,
      },
    ],
  },
  {
    level: 4,
    id: 'motion-constraints',
    tier: 'Foundations',
    titleEn: 'Level 4 — Arm Kinematics & Differential Geometry',
    titleId: 'Level 4 — Kinematika Lengan & Geometri Diferensial',
    descriptionEn: 'Articulated arm forward/inverse kinematics, Geometric Jacobians, kinematic singularities, and velocity manipulability ellipsoids.',
    descriptionId: 'Kinematika maju/invers lengan artikulasi, Jacobian Geometris, singularitas kinematik, dan elips manipulabilitas kecepatan.',
    badge: 'Differential Geometry',
    estimatedHours: 6,
    prerequisites: ['Level 3'],
    modules: [
      {
        id: '2dof-forward-kinematics',
        titleEn: '2-DOF Planar Arm Forward Kinematics (M18)',
        titleId: 'Kinematika Maju Lengan Robot 2-DOF (M18)',
        topicsCount: 6,
        href: '/learn/manipulation/2dof-forward-kinematics',
        isInteractive: true,
      },
      {
        id: '2dof-inverse-kinematics',
        titleEn: '2-DOF Planar Arm Inverse Kinematics (M19)',
        titleId: 'Kinematika Invers Lengan Robot 2-DOF (M19)',
        topicsCount: 6,
        href: '/learn/manipulation/2dof-inverse-kinematics',
        isInteractive: true,
      },
      {
        id: 'jacobian-and-singularity',
        titleEn: 'Jacobian Matrix & Velocity Ellipsoids (M20)',
        titleId: 'Matriks Jacobian & Elips Kecepatan (M20)',
        topicsCount: 6,
        href: '/learn/manipulation/jacobian-and-singularity',
        isInteractive: true,
      },
      {
        id: 'forward-inverse-kinematics',
        titleEn: 'Multi-Link Manipulator Forward & Inverse Kinematics',
        titleId: 'Kinematika Maju & Invers Manipulator Multi-Sendi',
        topicsCount: 6,
        href: '/learn/manipulation/forward-inverse-kinematics',
        isInteractive: true,
      },
    ],
  },

  // TIER 2: CORE AUTONOMY (LEVELS 5 - 8)
  {
    level: 5,
    id: 'sensors-perception',
    tier: 'Core Autonomy',
    titleEn: 'Level 5 — Sensors & Hardware Perception',
    titleId: 'Level 5 — Sensor & Persepsi Perangkat Keras',
    descriptionEn: 'Optical encoders, Inertial Measurement Units (IMU), 2D/3D LiDAR raycasting, and Gaussian measurement noise models.',
    descriptionId: 'Enkoder optik, Unit Pengukuran Inersia (IMU), raycasting LiDAR 2D/3D, dan model derau pengukuran Gaussian.',
    badge: 'Hardware Perception',
    estimatedHours: 5,
    prerequisites: ['Level 1', 'Level 2'],
    modules: [
      {
        id: 'sensor-fundamentals',
        titleEn: 'Sensor Fundamentals & Noise Characteristics',
        titleId: 'Fundamental Sensor & Karakteristik Derau',
        topicsCount: 6,
        href: '/learn/sensors/sensor-fundamentals',
        isInteractive: true,
      },
      {
        id: 'sensor-noise-and-uncertainty',
        titleEn: 'Sensor Noise Models & Gaussian Uncertainty (M08)',
        titleId: 'Model Derau Sensor & Ketidakpastian Gaussian (M08)',
        topicsCount: 6,
        href: '/learn/sensors/sensor-noise-and-uncertainty',
        isInteractive: true,
      },
      {
        id: 'wheel-odometry-and-drift',
        titleEn: 'Wheel Odometry & Systematic Dead Reckoning Drift (M09)',
        titleId: 'Odometri Roda & Akumulasi Galat Drift (M09)',
        topicsCount: 6,
        href: '/learn/sensors/wheel-odometry-and-drift',
        isInteractive: true,
      },
      {
        id: 'lidar-raycasting',
        titleEn: 'LiDAR Raycasting & Point Cloud Extraction (M21)',
        titleId: 'Raycasting LiDAR & Ekstraksi Point Cloud (M21)',
        topicsCount: 6,
        href: '/learn/sensors/lidar-raycasting',
        isInteractive: true,
      },
    ],
  },
  {
    level: 6,
    id: 'algorithms-planning',
    tier: 'Core Autonomy',
    titleEn: 'Level 6 — Motion Planning & Autonomous Exploration',
    titleId: 'Level 6 — Perencanaan Gerak & Eksplorasi Otonom',
    descriptionEn: 'Dijkstra, A* Heuristic Search, C-Space expansion, RRT/RRT* sampling planners, LAGS exploration, and 3D MAV safe flight corridors.',
    descriptionId: 'Dijkstra, Pencarian Heuristik A*, ekspansi C-Space, sampling RRT/RRT*, eksplorasi LAGS, dan koridor terbang aman 3D MAV.',
    badge: 'Navigation Planning',
    estimatedHours: 7,
    prerequisites: ['Level 2', 'Level 4'],
    modules: [
      {
        id: 'a-star',
        titleEn: 'A* Grid Search & Heuristic Planning',
        titleId: 'Pencarian Grid A* & Perencanaan Heuristik',
        topicsCount: 6,
        href: '/learn/planning/a-star',
        isInteractive: true,
      },
      {
        id: 'astar-vs-dijkstra-search',
        titleEn: 'A* vs Dijkstra Search Strategy Comparison (M15)',
        titleId: 'Komparasi Strategi Pencarian A* vs Dijkstra (M15)',
        topicsCount: 6,
        href: '/learn/planning/astar-vs-dijkstra-search',
        isInteractive: true,
      },
      {
        id: 'rrt-and-rrt-star',
        titleEn: 'Sampling-Based Planning: RRT & RRT*',
        titleId: 'Perencanaan Berbasis Sampel: RRT & RRT*',
        topicsCount: 6,
        href: '/learn/planning/rrt-and-rrt-star',
        isInteractive: true,
      },
      {
        id: 'rrt-sampling-planner',
        titleEn: 'RRT & RRT* Sampling Planner (M17)',
        titleId: 'Perencana Sampel RRT & RRT* (M17)',
        topicsCount: 6,
        href: '/learn/planning/rrt-sampling-planner',
        isInteractive: true,
      },
      {
        id: 'autonomous-exploration-lags',
        titleEn: 'Information-Theoretic Exploration & LAGS Strategy',
        titleId: 'Eksplorasi Berbasis Informasi & Strategi LAGS',
        topicsCount: 6,
        href: '/learn/planning/autonomous-exploration-lags',
        isInteractive: true,
      },
      {
        id: '3d-frontier-exploration-mav',
        titleEn: '3D Frontier Exploration & MAV Safe Flight Corridors',
        titleId: 'Eksplorasi Frontier 3D & Koridor Terbang MAV',
        topicsCount: 6,
        href: '/learn/planning/3d-frontier-exploration-mav',
        isInteractive: true,
      },
    ],
  },
  {
    level: 7,
    id: 'dynamics-control',
    tier: 'Core Autonomy',
    titleEn: 'Level 7 — Dynamics & Motion Control',
    titleId: 'Level 7 — Dinamika & Kendali Gerak',
    descriptionEn: 'Pure Pursuit lookahead geometry, Stanley cross-track non-linear feedback, PID controllers, and State-Space full feedback.',
    descriptionId: 'Kemudi geometris Pure Pursuit, umpan balik lateral Stanley, kontroler PID, dan umpan balik status penuh.',
    badge: 'Motion Control',
    estimatedHours: 6,
    prerequisites: ['Level 3', 'Level 6'],
    modules: [
      {
        id: 'path-tracking-error-geometry',
        titleEn: 'Path Tracking Error Geometry (M14)',
        titleId: 'Geometri Galat Pelacakan Jalur (M14)',
        topicsCount: 6,
        href: '/learn/control/path-tracking-error-geometry',
        isInteractive: true,
      },
      {
        id: 'pure-pursuit-path-tracking',
        titleEn: 'Pure Pursuit Path Tracking Control (M13)',
        titleId: 'Kendali Pelacakan Jalur Pure Pursuit (M13)',
        topicsCount: 6,
        href: '/learn/control/pure-pursuit-path-tracking',
        isInteractive: true,
      },
      {
        id: 'pure-pursuit-and-stanley',
        titleEn: 'Pure Pursuit & Stanley Non-Linear Steering',
        titleId: 'Kemudi Non-Linier Pure Pursuit & Stanley',
        topicsCount: 6,
        href: '/learn/control/pure-pursuit-and-stanley',
        isInteractive: true,
      },
      {
        id: 'pid-and-lqr-control',
        titleEn: 'PID Feedback Control & Transient Response (M12)',
        titleId: 'Kendali Umpan Balik PID & Respon Transien (M12)',
        topicsCount: 6,
        href: '/learn/control/pid-and-lqr-control',
        isInteractive: true,
      },
      {
        id: 'state-space-and-feedback',
        titleEn: 'State-Space Dynamics & Full-State Feedback (M27)',
        titleId: 'Dinamika Ruang Status & Umpan Balik Status (M27)',
        topicsCount: 6,
        href: '/learn/control/state-space-and-feedback',
        isInteractive: true,
      },
      {
        id: 'discrete-time-simulation',
        titleEn: 'Discrete-Time Simulation: Euler vs RK4 (M28)',
        titleId: 'Simulasi Waktu Diskret: Euler vs RK4 (M28)',
        topicsCount: 6,
        href: '/learn/control/discrete-time-simulation',
        isInteractive: true,
      },
    ],
  },
  {
    level: 8,
    id: 'state-estimation',
    tier: 'Core Autonomy',
    titleEn: 'Level 8 — Localization & State Estimation',
    titleId: 'Level 8 — Lokalisasi & Estimasi Status',
    descriptionEn: 'Recursive Bayesian Filtering, Monte Carlo Localization (MCL), Non-linear Extended Kalman Filter (EKF), and Multi-Sensor Fusion.',
    descriptionId: 'Filter Bayesian Rekursif, Lokalisasi Monte Carlo (MCL), Extended Kalman Filter (EKF) non-linear, dan Fusi Multi-Sensor.',
    badge: 'State Estimation',
    estimatedHours: 6,
    prerequisites: ['Level 5', 'Level 7'],
    modules: [
      {
        id: 'localization-fundamentals',
        titleEn: 'Robot Localization Fundamentals & Taxonomy',
        titleId: 'Fundamental & Taksonomi Lokalisasi Robot',
        topicsCount: 6,
        href: '/learn/estimation/localization-fundamentals',
        isInteractive: true,
      },
      {
        id: 'bayes-filter-and-kalman',
        titleEn: '1D Bayesian Filtering & Kalman Prediction-Correction',
        titleId: 'Filter Bayesian 1D & Prediksi-Koreksi Kalman',
        topicsCount: 6,
        href: '/learn/estimation/bayes-filter-and-kalman',
        isInteractive: true,
      },
      {
        id: 'ekf-localization',
        titleEn: 'Extended Kalman Filter (EKF) 2D Localization',
        titleId: 'Lokalisasi 2D Extended Kalman Filter (EKF)',
        topicsCount: 6,
        href: '/learn/estimation/ekf-localization',
        isInteractive: true,
      },
      {
        id: 'sensor-fusion-imu-gps-odometry',
        titleEn: 'Multi-Sensor Fusion: Wheel Odometry + IMU + GPS (M30)',
        titleId: 'Fusi Multi-Sensor: Odometri + IMU + GPS (M30)',
        topicsCount: 6,
        href: '/learn/estimation/sensor-fusion-imu-gps-odometry',
        isInteractive: true,
      },
      {
        id: 'histogram-filter-localization',
        titleEn: 'Discrete Grid Histogram Filter Localization',
        titleId: 'Lokalisasi Filter Histogram Grid Diskrit',
        topicsCount: 6,
        href: '/learn/estimation/histogram-filter-localization',
        isInteractive: true,
      },
      {
        id: 'mcl-particle-filter',
        titleEn: 'Monte Carlo Localization Particle Filters (M24)',
        titleId: 'Filter Partikel Monte Carlo Localization (M24)',
        topicsCount: 6,
        href: '/learn/estimation/mcl-particle-filter',
        isInteractive: true,
      },
    ],
  },

  // TIER 3: SPATIAL INTELLIGENCE & SLAM (LEVELS 9 - 12)
  {
    level: 9,
    id: 'mapping',
    tier: 'Spatial Intelligence',
    titleEn: 'Level 9 — Spatial Mapping & Point Cloud Processing',
    titleId: 'Level 9 — Pemetaan Spasial & Pemrosesan Point Cloud',
    descriptionEn: 'Log-Odds Occupancy Grid Mapping, Gaussian continuous grid maps, raycasting, LiDAR-to-grid transforms, K-Means clustering, and bounding box fitting.',
    descriptionId: 'Pemetaan Grid Okupansi Log-Odds, peta grid kontinyu Gaussian, raycasting, transformasi LiDAR-ke-grid, klasterisasi K-Means, dan pencocokan kotak pembatas.',
    badge: 'Spatial Modeling',
    estimatedHours: 6,
    prerequisites: ['Level 5', 'Level 8'],
    modules: [
      {
        id: 'occupancy-grid-mapping',
        titleEn: 'Log-Odds Occupancy Grid Mapping (M22)',
        titleId: 'Pemetaan Grid Okupansi Log-Odds (M22)',
        topicsCount: 6,
        href: '/learn/perception/occupancy-grid-mapping',
        isInteractive: true,
      },
      {
        id: 'gaussian-grid-map',
        titleEn: 'Gaussian Grid Mapping & Kernel Density Estimation',
        titleId: 'Pemetaan Grid Gaussian & Estimasi Kerapatan Kernel',
        topicsCount: 6,
        href: '/learn/perception/gaussian-grid-map',
        isInteractive: true,
      },
      {
        id: 'raycasting-grid-map',
        titleEn: 'Raycasting Grid Map Generation & Bresenham Algorithm',
        titleId: 'Pembangkitan Peta Grid Raycasting & Algoritma Bresenham',
        topicsCount: 6,
        href: '/learn/perception/raycasting-grid-map',
        isInteractive: true,
      },
      {
        id: 'lidar-to-grid-map',
        titleEn: 'LiDAR Point Cloud to Grid Map Coordinate Transforms',
        titleId: 'Transformasi Koordinat Point Cloud LiDAR ke Peta Grid',
        topicsCount: 6,
        href: '/learn/perception/lidar-to-grid-map',
        isInteractive: true,
      },
      {
        id: 'kmeans-object-clustering',
        titleEn: 'K-Means Point Cloud Spatial Object Clustering',
        titleId: 'Klasterisasi Objek Spasial Point Cloud K-Means',
        topicsCount: 6,
        href: '/learn/perception/kmeans-object-clustering',
        isInteractive: true,
      },
      {
        id: 'rectangle-fitting',
        titleEn: 'L-Shape Search & Minimum Area Bounding Box Fitting',
        titleId: 'Pencarian Pola L & Pencocokan Bounding Box Area Minimum',
        topicsCount: 6,
        href: '/learn/perception/rectangle-fitting',
        isInteractive: true,
      },
    ],
  },
  {
    level: 10,
    id: 'slam',
    tier: 'Spatial Intelligence',
    titleEn: 'Level 10 — Simultaneous Localization & Mapping (SLAM)',
    titleId: 'Level 10 — Lokalisasi & Pemetaan Simultan (SLAM)',
    descriptionEn: 'ICP scan matching, FastSLAM 1.0 Rao-Blackwellized particle filter, 2D LiDAR submap loop closure, 3D LiDAR LOAM, and Factor Graph SLAM.',
    descriptionId: 'Pencocokan pindaian ICP, FastSLAM 1.0 Rao-Blackwellized, loop closure submap LiDAR 2D, LiDAR 3D LOAM, dan SLAM Graf Faktor.',
    badge: 'Full Spatial Autonomy',
    estimatedHours: 8,
    prerequisites: ['Level 8', 'Level 9'],
    modules: [
      {
        id: 'slam-fundamentals',
        titleEn: 'SLAM Fundamentals & System Architecture',
        titleId: 'Fundamental SLAM & Arsitektur Sistem',
        topicsCount: 6,
        href: '/learn/advanced/slam-fundamentals',
        isInteractive: true,
      },
      {
        id: 'icp-scan-matching',
        titleEn: 'Iterative Closest Point (ICP) Scan Matching (M23)',
        titleId: 'Pencocokan Pindaian Iterative Closest Point (ICP) (M23)',
        topicsCount: 6,
        href: '/learn/advanced/icp-scan-matching',
        isInteractive: true,
      },
      {
        id: 'fastslam-1',
        titleEn: 'FastSLAM 1.0 Rao-Blackwellized Particle Filtering',
        titleId: 'FastSLAM 1.0 Filter Partikel Rao-Blackwellized',
        topicsCount: 6,
        href: '/learn/advanced/fastslam-1',
        isInteractive: true,
      },
      {
        id: '2d-lidar-slam',
        titleEn: '2D LiDAR SLAM, Submaps & Loop Closure Optimization',
        titleId: 'SLAM LiDAR 2D, Submap & Optimasi Loop Closure',
        topicsCount: 6,
        href: '/learn/advanced/2d-lidar-slam',
        isInteractive: true,
      },
      {
        id: '3d-lidar-and-vslam',
        titleEn: '3D LiDAR SLAM (LOAM/FAST-LIO) & Visual SLAM',
        titleId: 'SLAM LiDAR 3D (LOAM/FAST-LIO) & Visual SLAM',
        topicsCount: 6,
        href: '/learn/advanced/3d-lidar-and-vslam',
        isInteractive: true,
      },
      {
        id: 'factor-graph-optimization',
        titleEn: 'Factor Graph SLAM & Non-Linear Least Squares Optimizer',
        titleId: 'Graf Faktor SLAM & Optimizer Kuadrat Terkecil Non-Linear',
        topicsCount: 6,
        href: '/learn/advanced/factor-graph-optimization',
        isInteractive: true,
      },
    ],
  },
  {
    level: 11,
    id: 'frontier-research',
    tier: 'Spatial Intelligence',
    titleEn: 'Level 11 — Frontier SLAM & Volumetric Radiance Fields',
    titleId: 'Level 11 — SLAM Terdepan & Bidang Pancaran Volumetrik',
    descriptionEn: '3D Gaussian Splatting SLAM (3DGS-SLAM), differentiable rasterization, photometric bundle adjustment, and continuous neural scene representation.',
    descriptionId: '3D Gaussian Splatting SLAM (3DGS-SLAM), rasterisasi diferensiabel, bundle adjustment fotometrik, dan representasi pemandangan neural.',
    badge: 'Frontier SLAM',
    estimatedHours: 6,
    prerequisites: ['Level 10'],
    modules: [
      {
        id: '3d-gaussian-splatting-slam',
        titleEn: '3D Gaussian Splatting SLAM (3DGS-SLAM) & Radiance Fields',
        titleId: '3D Gaussian Splatting SLAM (3DGS-SLAM) & Bidang Pancaran',
        topicsCount: 6,
        href: '/learn/advanced/3d-gaussian-splatting-slam',
        isInteractive: true,
      },
    ],
  },
  {
    level: 12,
    id: 'robot-ai-vla',
    tier: 'Spatial Intelligence',
    titleEn: 'Level 12 — Robot Learning, Sim-to-Real & VLA Policies',
    titleId: 'Level 12 — Pembelajaran Robot, Sim-to-Real & Kebijakan VLA',
    descriptionEn: 'Physics domain randomization, sim-to-real transfer, Vision-Language-Action (VLA) foundation models, and conditional Denoising Diffusion policies.',
    descriptionId: 'Randomisasi domain fisik, transfer sim-to-real, model fondasi Vision-Language-Action (VLA), dan kebijakan Denoising Diffusion.',
    badge: 'Embodied AI',
    estimatedHours: 6,
    prerequisites: ['Level 11'],
    modules: [
      {
        id: 'sim-to-real-and-domain-randomization',
        titleEn: 'Sim-to-Real Transfer, Domain Randomization & RL',
        titleId: 'Transfer Sim-to-Real, Randomisasi Domain & RL',
        topicsCount: 6,
        href: '/learn/advanced/sim-to-real-and-domain-randomization',
        isInteractive: true,
      },
      {
        id: 'vla-and-diffusion-policies',
        titleEn: 'Vision-Language-Action (VLA) & Denoising Diffusion Policies',
        titleId: 'Vision-Language-Action (VLA) & Kebijakan Denoising Diffusion',
        topicsCount: 6,
        href: '/learn/advanced/vla-and-diffusion-policies',
        isInteractive: true,
      },
    ],
  },

  // TIER 4: ADVANCED EMBODIMENTS & SPECIALIZATIONS (LEVELS 13 - 20)
  {
    level: 13,
    id: 'swarms-consensus',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 18 — Multi-Agent Swarms & Formation Control',
    titleId: 'Level 18 — Kawanan Multi-Agent & Kendali Formasi',
    descriptionEn: 'Decentralized communication graphs, Graph Laplacian consensus dynamics, leader-follower tracking, and collision-free formation flocking.',
    descriptionId: 'Graf komunikasi terdesentralisasi, dinamika konsensus Laplacian, pelacakan leader-follower, dan formasi kawanan bebas tabrakan.',
    badge: 'Swarm Intelligence',
    estimatedHours: 6,
    prerequisites: ['Level 7'],
    modules: [
      {
        id: 'laplacian-consensus',
        titleEn: 'Graph Laplacian Consensus & Swarm Coordination (M25)',
        titleId: 'Konsensus Graf Laplacian & Koordinasi Kawanan (M25)',
        topicsCount: 6,
        href: '/learn/advanced/laplacian-consensus',
        isInteractive: true,
      },
      {
        id: 'formation-control-and-swarms',
        titleEn: 'Formation Control & Leader-Follower Swarms (M26)',
        titleId: 'Kendali Formasi & Kawanan Robot Leader-Follower (M26)',
        topicsCount: 6,
        href: '/learn/advanced/formation-control-and-swarms',
        isInteractive: true,
      },
    ],
  },
];
