export interface CurriculumLevel {
  level: number;
  id: string;
  tier: 'Foundations' | 'Core Autonomy' | 'Spatial Intelligence' | 'Advanced Embodiments';
  titleEn: string;
  titleId: string;
  descriptionEn: string;
  descriptionId: string;
  badge: string;
  estimatedHours: number;
  prerequisites: string[];
  modules: {
    id: string;
    titleEn: string;
    titleId: string;
    topicsCount: number;
    href: string;
    isInteractive: boolean;
  }[];
}

export const MASTER_CURRICULUM_LEVELS: CurriculumLevel[] = [
  // TIER 1: FOUNDATIONS (LEVELS 0 - 4)
  {
    level: 0,
    id: 'orientation',
    tier: 'Foundations',
    titleEn: 'Level 0 — Robotics Orientation',
    titleId: 'Level 0 — Orientasi Robotika',
    descriptionEn: 'Introduction to cyber-physical autonomy, Sense-Plan-Act loops, hardware/software anatomy, and robot taxonomy.',
    descriptionId: 'Pengantar sistem siber-fisik otonom, siklus Sense-Plan-Act, anatomi perangkat keras/lunak, dan klasifikasi robot.',
    badge: 'Beginner Friendly',
    estimatedHours: 2,
    prerequisites: ['None'],
    modules: [
      {
        id: 'intro-to-robotics',
        titleEn: 'Introduction to Autonomous Robotics & Classifications',
        titleId: 'Pengantar Robotika Otonom & Klasifikasinya',
        topicsCount: 8,
        href: '/learn/fundamentals/intro-to-robotics',
        isInteractive: true,
      },
    ],
  },
  {
    level: 1,
    id: 'mathematics',
    tier: 'Foundations',
    titleEn: 'Level 1 — Mathematical & Geometric Foundations',
    titleId: 'Level 1 — Fondasi Matematika & Geometri',
    descriptionEn: 'Scalars, Vectors, Matrices in SE(2)/SO(3), Euler Angles, Quaternions, Probability, and Least Squares Optimization.',
    descriptionId: 'Skalar, Vektor, Matriks SE(2)/SO(3), Sudut Euler, Kuaternion, Probabilitas, dan Optimasi Kuadrat Terkecil.',
    badge: 'Core Prerequisite',
    estimatedHours: 6,
    prerequisites: ['Level 0'],
    modules: [
      {
        id: 'mathematical-foundations',
        titleEn: 'Mathematical Foundations for Robotics',
        titleId: 'Fundamental Matematika untuk Robotika',
        topicsCount: 6,
        href: '/learn/fundamentals/mathematical-foundations',
        isInteractive: true,
      },
    ],
  },
  {
    level: 2,
    id: 'coordinate-frames',
    tier: 'Foundations',
    titleEn: 'Level 2 — Coordinate Frames & Transformations',
    titleId: 'Level 2 — Kerangka Koordinat & Transformasi',
    descriptionEn: 'World, Robot, and Sensor Frames. 2D/3D Homogeneous Transformation Matrices, Rotation Composition, and Frame Chains.',
    descriptionId: 'Kerangka Acuan Dunia, Robot, dan Sensor. Matriks Transformasi Homogen 2D/3D, Komposisi Rotasi, dan Rantai Kerangka.',
    badge: 'Spatial Math',
    estimatedHours: 5,
    prerequisites: ['Level 1'],
    modules: [
      {
        id: '2d-geometry',
        titleEn: '2D Planar Geometry & Homogeneous Transforms SE(2)',
        titleId: 'Geometri Planar 2D & Transformasi Homogen SE(2)',
        topicsCount: 6,
        href: '/learn/fundamentals/2d-geometry',
        isInteractive: true,
      },
      {
        id: '3d-geometry',
        titleEn: '3D Spatial Geometry & SO(3) Rotations',
        titleId: 'Geometri Spasial 3D & Rotasi SO(3)',
        topicsCount: 6,
        href: '/learn/fundamentals/3d-geometry',
        isInteractive: true,
      },
    ],
  },
  {
    level: 3,
    id: 'kinematics',
    tier: 'Foundations',
    titleEn: 'Level 3 — Robot Modeling & Kinematics',
    titleId: 'Level 3 — Pemodelan Robot & Kinematika',
    descriptionEn: 'Differential-drive unicycle models, Instantaneous Center of Curvature (ICC), Pfaffian non-holonomic constraints, and Forward/Inverse Kinematics.',
    descriptionId: 'Model unicycle roda diferensial, Pusat Kurvatur Seketika (ICC), kendala non-holonomik Pfaffian, dan Kinematika Maju/Invers.',
    badge: 'Mechanical Modeling',
    estimatedHours: 5,
    prerequisites: ['Level 2'],
    modules: [
      {
        id: 'velocity-kinematics-2d',
        titleEn: '2D Velocity Kinematics & Unicycle Models',
        titleId: 'Kinematika Kecepatan 2D & Model Unicycle',
        topicsCount: 6,
        href: '/learn/fundamentals/velocity-kinematics-2d',
        isInteractive: true,
      },
    ],
  },
  {
    level: 4,
    id: 'motion-geometry',
    tier: 'Foundations',
    titleEn: 'Level 4 — Robot Motion & Differential Geometry',
    titleId: 'Level 4 — Gerak Robot & Geometri Diferensial',
    descriptionEn: 'Spatial twists in se(3), skew-symmetric operators, Geometric Manipulator Jacobians, singularities, and velocity ellipsoids.',
    descriptionId: 'Spatial twist pada se(3), operator skew-symmetric, Jacobian Geometris Manipulator, singularitas, dan elipsoid kecepatan.',
    badge: 'Differential Geometry',
    estimatedHours: 6,
    prerequisites: ['Level 3'],
    modules: [
      {
        id: 'velocity-kinematics-3d',
        titleEn: '3D Velocity Kinematics & Geometric Jacobians',
        titleId: 'Kinematika Kecepatan 3D & Jacobian Geometris',
        topicsCount: 6,
        href: '/learn/fundamentals',
        isInteractive: true,
      },
    ],
  },

  // TIER 2: CORE AUTONOMY (LEVELS 5 - 8)
  {
    level: 5,
    id: 'sensors-perception',
    tier: 'Core Autonomy',
    titleEn: 'Level 5 — Sensors & Perception',
    titleId: 'Level 5 — Sensor & Persepsi',
    descriptionEn: 'Optical encoders, Inertial Measurement Units (IMU), 2D/3D LiDAR raycasting, depth cameras, and Gaussian measurement noise models.',
    descriptionId: 'Enkoder optik, Unit Pengukuran Inersia (IMU), raycasting LiDAR 2D/3D, kamera kedalaman, dan model derau Gaussian.',
    badge: 'Hardware Perception',
    estimatedHours: 5,
    prerequisites: ['Level 1', 'Level 2'],
    modules: [
      {
        id: 'lidar-raycast',
        titleEn: 'LiDAR Raycasting & Sensor Noise Models',
        titleId: 'Raycasting LiDAR & Model Derau Sensor',
        topicsCount: 5,
        href: '/learn/mapping',
        isInteractive: true,
      },
    ],
  },
  {
    level: 6,
    id: 'planning-trajectory',
    tier: 'Core Autonomy',
    titleEn: 'Level 6 — Path & Trajectory Planning',
    titleId: 'Level 6 — Perencanaan Jalur & Trajektori',
    descriptionEn: 'Dijkstra, A* Heuristic Search, Configuration Space (C-Space) expansion, RRT, RRT*, and Quintic Polynomial Splines.',
    descriptionId: 'Dijkstra, Pencarian Heuristik A*, ekspansi Ruang Konfigurasi (C-Space), RRT, RRT*, dan Spline Polinomial Kuintik.',
    badge: 'Navigation Planning',
    estimatedHours: 7,
    prerequisites: ['Level 2', 'Level 4'],
    modules: [
      {
        id: 'a-star',
        titleEn: 'A* Grid Search & Admissible Heuristics',
        titleId: 'Pencarian Grid A* & Heuristik Admisibel',
        topicsCount: 6,
        href: '/learn/planning/a-star',
        isInteractive: true,
      },
    ],
  },
  {
    level: 7,
    id: 'dynamics-control',
    tier: 'Core Autonomy',
    titleEn: 'Level 7 — Robot Dynamics & Control',
    titleId: 'Level 7 — Dinamika Robot & Kendali',
    descriptionEn: 'Pure Pursuit lookahead geometry, Stanley cross-track non-linear feedback, PID controllers, and Newton-Euler / Euler-Lagrange dynamics.',
    descriptionId: 'Kemudi geometris Pure Pursuit, umpan balik lateral Stanley, kontroler PID, dan dinamika Newton-Euler / Euler-Lagrange.',
    badge: 'Motion Control',
    estimatedHours: 6,
    prerequisites: ['Level 3', 'Level 6'],
    modules: [
      {
        id: 'pure-pursuit-and-stanley',
        titleEn: 'Pure Pursuit & Stanley Path Tracking',
        titleId: 'Pelacakan Jalur Pure Pursuit & Stanley',
        topicsCount: 6,
        href: '/learn/control/pure-pursuit-and-stanley',
        isInteractive: true,
      },
    ],
  },
  {
    level: 8,
    id: 'localization-estimation',
    tier: 'Core Autonomy',
    titleEn: 'Level 8 — Localization & State Estimation',
    titleId: 'Level 8 — Lokalisasi & Estimasi Status',
    descriptionEn: 'Recursive Bayesian Filtering, Chapman-Kolmogorov motion prediction, Monte Carlo Localization (MCL) Particle Filters, and EKF.',
    descriptionId: 'Filter Bayesian Rekursif, prediksi gerak Chapman-Kolmogorov, Filter Partikel Monte Carlo (MCL), dan EKF.',
    badge: 'State Estimation',
    estimatedHours: 6,
    prerequisites: ['Level 5', 'Level 7'],
    modules: [
      {
        id: 'mcl-particle-filter',
        titleEn: 'Monte Carlo Localization Particle Filters',
        titleId: 'Filter Partikel Monte Carlo Localization',
        topicsCount: 5,
        href: '/learn/localization/mcl-particle-filter',
        isInteractive: true,
      },
    ],
  },

  // TIER 3: SPATIAL INTELLIGENCE & SLAM (LEVELS 9 - 12)
  {
    level: 9,
    id: 'mapping',
    tier: 'Spatial Intelligence',
    titleEn: 'Level 9 — Spatial Mapping & Costmaps',
    titleId: 'Level 9 — Pemetaan Spasial & Costmap',
    descriptionEn: 'Log-Odds Bayesian Occupancy Grid Mapping, Euclidean Distance Transforms (EDT), costmap inflation layers, and topological maps.',
    descriptionId: 'Pemetaan Grid Okupansi Log-Odds Bayesian, Euclidean Distance Transform (EDT), lapisan inflasi costmap, dan peta topologis.',
    badge: 'Spatial Modeling',
    estimatedHours: 5,
    prerequisites: ['Level 5', 'Level 8'],
    modules: [
      {
        id: 'occupancy-grid-mapping',
        titleEn: 'Log-Odds Occupancy Grid Mapping',
        titleId: 'Pemetaan Grid Okupansi Log-Odds',
        topicsCount: 5,
        href: '/learn/mapping/occupancy-grid-mapping',
        isInteractive: true,
      },
    ],
  },
  {
    level: 10,
    id: 'slam',
    tier: 'Spatial Intelligence',
    titleEn: 'Level 10 — Simultaneous Localization & Mapping (SLAM)',
    titleId: 'Level 10 — Lokalisasi & Pemetaan Simultan (SLAM)',
    descriptionEn: 'Chicken-and-egg spatial dilemma, Iterative Closest Point (ICP) scan registration, closed-form SVD rotation, and pose-graph optimization.',
    descriptionId: 'Dilema ayam-dan-telur spasial, registrasi scan Iterative Closest Point (ICP), rotasi analitik SVD, dan optimasi pose-graph.',
    badge: 'Full Spatial Autonomy',
    estimatedHours: 7,
    prerequisites: ['Level 8', 'Level 9'],
    modules: [
      {
        id: 'icp-scan-matching',
        titleEn: 'Iterative Closest Point (ICP) Scan Matching',
        titleId: 'Pencocokan Pindaian Iterative Closest Point (ICP)',
        topicsCount: 5,
        href: '/learn/slam/icp-scan-matching',
        isInteractive: true,
      },
    ],
  },
  {
    level: 11,
    id: 'navigation',
    tier: 'Spatial Intelligence',
    titleEn: 'Level 11 — Integrated Autonomous Navigation',
    titleId: 'Level 11 — Navigasi Otonom Terintegrasi',
    descriptionEn: 'Global path planning + local obstacle avoidance, dynamic window approach (DWA), timed elastic bands (TEB), and recovery behaviors.',
    descriptionId: 'Perencanaan jalur global + penghindaran rintangan lokal, Dynamic Window Approach (DWA), TEB, dan perilaku pemulihan (recovery).',
    badge: 'Navigation Stack',
    estimatedHours: 6,
    prerequisites: ['Level 6', 'Level 7', 'Level 10'],
    modules: [
      {
        id: 'integrated-navigation',
        titleEn: 'Global & Local Navigation Pipeline',
        titleId: 'Pipeline Navigasi Global & Lokal',
        topicsCount: 5,
        href: '/learn/planning',
        isInteractive: true,
      },
    ],
  },
  {
    level: 12,
    id: 'autonomous-systems',
    tier: 'Spatial Intelligence',
    titleEn: 'Level 12 — Autonomous Systems Architecture',
    titleId: 'Level 12 — Arsitektur Sistem Otonom',
    descriptionEn: 'Hierarchical state machines, Behavior Trees (BT), mission planners, fault monitoring, and safety-critical watchdog systems.',
    descriptionId: 'Mesin status hierarkis, Behavior Trees (BT), perencana misi, pemantau kegagalan, dan sistem keselamatan kritis.',
    badge: 'System Architecture',
    estimatedHours: 5,
    prerequisites: ['Level 11'],
    modules: [
      {
        id: 'behavior-trees',
        titleEn: 'Behavior Trees & Autonomy Executive',
        titleId: 'Behavior Trees & Eksekutif Otonomi',
        topicsCount: 4,
        href: '/learn/fundamentals',
        isInteractive: true,
      },
    ],
  },

  // TIER 4: ADVANCED EMBODIMENTS & SPECIALIZATIONS (LEVELS 13 - 20)
  {
    level: 13,
    id: 'ros-software',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 13 — Robotics Software Engineering & ROS 2',
    titleId: 'Level 13 — Rekayasa Perangkat Lunak Robotika & ROS 2',
    descriptionEn: 'ROS 2 DDS middleware, nodes, topics, services, actions, URDF robot description models, and Gazebo physics simulation.',
    descriptionId: 'Middleware ROS 2 DDS, node, topik, layanan, aksi, model deskripsi robot URDF, dan simulasi fisik Gazebo.',
    badge: 'Software Engineering',
    estimatedHours: 6,
    prerequisites: ['Level 3', 'Level 12'],
    modules: [
      {
        id: 'ros2-architecture',
        titleEn: 'ROS 2 Computation Graph & URDF Models',
        titleId: 'Graf Komputasi ROS 2 & Model URDF',
        topicsCount: 5,
        href: '/learn/fundamentals',
        isInteractive: true,
      },
    ],
  },
  {
    level: 14,
    id: 'manipulation',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 14 — Manipulation Robotics & Articulated Arms',
    titleId: 'Level 14 — Robotika Manipulasi & Lengan Bersendi',
    descriptionEn: 'Forward/Inverse Kinematics (IK), Denavit-Hartenberg (DH) parameters, analytical & numerical IK, grasp planning, and MoveIt pipeline.',
    descriptionId: 'Kinematika Maju/Invers (IK), parameter Denavit-Hartenberg (DH), IK analitik & numerik, perencanaan genggaman, dan MoveIt.',
    badge: 'Articulated Arms',
    estimatedHours: 7,
    prerequisites: ['Level 4', 'Level 7'],
    modules: [
      {
        id: 'manipulator-kinematics',
        titleEn: '6-DOF Manipulator Forward & Inverse Kinematics',
        titleId: 'Kinematika Maju & Invers Manipulator 6-DOF',
        topicsCount: 6,
        href: '/learn/fundamentals',
        isInteractive: true,
      },
    ],
  },
  {
    level: 15,
    id: 'aerial',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 15 — Aerial Robotics & Quadrotors',
    titleId: 'Level 15 — Robotika Udara & Quadrotor',
    descriptionEn: '6-DOF quadrotor flight dynamics, SE(3) geometric attitude control, differential flatness, and minimum-snap trajectory generation.',
    descriptionId: 'Dinamika penerbangan quadrotor 6-DOF, kendali sikap geometris SE(3), diferensial flatness, dan pembuatan trajektori minimum-snap.',
    badge: 'Flight Dynamics',
    estimatedHours: 7,
    prerequisites: ['Level 2', 'Level 7'],
    modules: [
      {
        id: 'quadrotor-dynamics',
        titleEn: 'Quadrotor Flight Dynamics & Minimum-Snap',
        titleId: 'Dinamika Terbang Quadrotor & Minimum-Snap',
        topicsCount: 5,
        href: '/learn/control',
        isInteractive: true,
      },
    ],
  },
  {
    level: 16,
    id: 'legged',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 16 — Legged Robotics & Quadruped Locomotion',
    titleId: 'Level 16 — Robotika Berkaki & Lokomosi Quadruped',
    descriptionEn: 'Zero Moment Point (ZMP), Linear Inverted Pendulum Model (LIPM), gait sequencing (trot, bound, gallop), and whole-body control (WBC).',
    descriptionId: 'Zero Moment Point (ZMP), Linear Inverted Pendulum Model (LIPM), sekuens gaya berjalan (trot, bound, gallop), dan Whole-Body Control.',
    badge: 'Legged Locomotion',
    estimatedHours: 7,
    prerequisites: ['Level 4', 'Level 7'],
    modules: [
      {
        id: 'legged-locomotion',
        titleEn: 'Inverted Pendulum Dynamics & Gait Planning',
        titleId: 'Dinamika Pendulum Terbalik & Perencanaan Gait',
        topicsCount: 5,
        href: '/learn/control',
        isInteractive: true,
      },
    ],
  },
  {
    level: 17,
    id: 'learning-robotics',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 17 — Learning-Based Robotics & RL',
    titleId: 'Level 17 — Robotika Berbasis Pembelajaran & RL',
    descriptionEn: 'Reinforcement learning for locomotion, sim-to-real transfer, domain randomization, imitation learning, and vision-language-action (VLA) models.',
    descriptionId: 'Reinforcement Learning untuk lokomosi, transfer sim-to-real, domain randomization, imitation learning, dan model VLA.',
    badge: 'AI & Machine Learning',
    estimatedHours: 8,
    prerequisites: ['Level 1', 'Level 12'],
    modules: [
      {
        id: 'reinforcement-learning-robotics',
        titleEn: 'Policy Gradients & Sim-to-Real Transfer',
        titleId: 'Policy Gradients & Transfer Sim-to-Real',
        topicsCount: 5,
        href: '/learn/fundamentals',
        isInteractive: true,
      },
    ],
  },
  {
    level: 18,
    id: 'multi-agent',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 18 — Multi-Agent Robotics & Swarm Intelligence',
    titleId: 'Level 18 — Robotika Multi-Agent & Kecerdasan Kawanan',
    descriptionEn: 'Decentralized communication graph topologies, Graph Laplacian consensus dynamics, leader-follower formations, and Reynolds flocking.',
    descriptionId: 'Topologi graf komunikasi terdesentralisasi, dinamika konsensus Graph Laplacian, formasi leader-follower, dan kawanan Reynolds.',
    badge: 'Swarm Intelligence',
    estimatedHours: 6,
    prerequisites: ['Level 1', 'Level 7'],
    modules: [
      {
        id: 'laplacian-consensus',
        titleEn: 'Graph Laplacian Consensus & Swarm Coordination',
        titleId: 'Konsensus Graf Laplacian & Koordinasi Kawanan',
        topicsCount: 5,
        href: '/learn/multi-agent/laplacian-consensus',
        isInteractive: true,
      },
    ],
  },
  {
    level: 19,
    id: 'advanced-math',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 19 — Advanced Robotics Mathematics & Lie Groups',
    titleId: 'Level 19 — Matematika Lanjutan & Grup Lie untuk Robotika',
    descriptionEn: 'Matrix Lie groups SO(3)/SE(3), Lie algebras so(3)/se(3), exponential map, adjoint representations, and factor graph optimization.',
    descriptionId: 'Grup Lie matriks SO(3)/SE(3), aljabar Lie so(3)/se(3), pemetaan eksponensial, representasi adjoint, dan optimasi graf faktor.',
    badge: 'Lie Groups & Manifolds',
    estimatedHours: 8,
    prerequisites: ['Level 1', 'Level 4', 'Level 10'],
    modules: [
      {
        id: 'lie-theory-robotics',
        titleEn: 'Lie Groups, Lie Algebras & Manifold Optimization',
        titleId: 'Grup Lie, Aljabar Lie & Optimasi Manifold',
        topicsCount: 6,
        href: '/learn/fundamentals',
        isInteractive: true,
      },
    ],
  },
  {
    level: 20,
    id: 'research-emerging',
    tier: 'Advanced Embodiments',
    titleEn: 'Level 20 — Robotics Research & Emerging Topics',
    titleId: 'Level 20 — Riset Robotika & Topik Terdepan',
    descriptionEn: 'Soft robotics continuum mechanics, neural radiance fields (NeRF/3DGS) for robotics, micro-robotics, and open benchmark problems.',
    descriptionId: 'Mekanika kontinuum soft robotics, Neural Radiance Fields (NeRF/3DGS), mikro-robotika, dan tolok ukur riset terbuka.',
    badge: 'Frontier Research',
    estimatedHours: 8,
    prerequisites: ['Level 10', 'Level 18', 'Level 19'],
    modules: [
      {
        id: 'frontier-robotics',
        titleEn: 'Frontier Robotics: NeRF SLAM & Soft Continuum',
        titleId: 'Robotika Terdepan: NeRF SLAM & Kontinuum Fleksibel',
        topicsCount: 5,
        href: '/learn/fundamentals',
        isInteractive: true,
      },
    ],
  },
];
