export interface LessonRegistryItem {
  id: string;
  slug: string;
  domain: string;
  level: number;
  tier: 'Foundations' | 'Core Autonomy' | 'Spatial Intelligence' | 'Advanced Embodiments';
  titleEn: string;
  titleId: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  estimatedMinutes: number;
  prerequisites: string[];
  platforms: ('manipulator' | 'mobile' | 'aerial' | 'marine' | 'legged')[];
  components: string[];
  interactive: boolean;
  references: string[];
}

export interface DomainRegistryItem {
  id: string;
  slug: string;
  titleEn: string;
  titleId: string;
  descriptionEn: string;
  descriptionId: string;
  levelRange: string;
  iconName: string;
  primaryEmbodiment: string;
}

export const DOMAIN_REGISTRY: DomainRegistryItem[] = [
  {
    id: 'fundamentals',
    slug: 'fundamentals',
    titleEn: 'Robotics Fundamentals',
    titleId: 'Fondasi Robotika',
    descriptionEn: 'Cyber-physical systems, Sense-Plan-Act loops, hardware/software anatomy, and robot morphology.',
    descriptionId: 'Sistem siber-fisik, siklus Sense-Plan-Act, anatomi perangkat keras/lunak, dan morfologi robot.',
    levelRange: 'Level 0',
    iconName: 'Compass',
    primaryEmbodiment: 'All Embodiments',
  },
  {
    id: 'mathematics',
    slug: 'mathematics',
    titleEn: 'Mathematical Foundations',
    titleId: 'Fondasi Matematika',
    descriptionEn: 'Scalars, 2D/3D vectors, Pythagorean geometry, unit directions, dot product projections, and matrix algebra.',
    descriptionId: 'Skalar, vektor 2D/3D, geometri Pythagoras, arah satuan, proyeksi perkalian titik, dan aljabar matriks.',
    levelRange: 'Level 1',
    iconName: 'Grid',
    primaryEmbodiment: 'All Embodiments',
  },
  {
    id: 'geometry',
    slug: 'geometry',
    titleEn: 'Geometry & Transformations',
    titleId: 'Geometri & Transformasi',
    descriptionEn: 'Coordinate frames, Homogeneous transforms in SE(2)/SE(3), SO(3) Euler rotations, and unit quaternions.',
    descriptionId: 'Kerangka acuan, transformasi homogen SE(2)/SE(3), rotasi Euler SO(3), dan kuaternion satuan.',
    levelRange: 'Level 2',
    iconName: 'Box',
    primaryEmbodiment: 'Manipulator, Mobile, UAV, Marine',
  },
  {
    id: 'kinematics',
    slug: 'kinematics',
    titleEn: 'Robot Kinematics',
    titleId: 'Kinematika Robot',
    descriptionEn: 'Differential unicycle modeling, Instantaneous Center of Curvature (ICC), and Pfaffian non-holonomic constraints.',
    descriptionId: 'Pemodelan unicycle diferensial, Pusat Kurvatur Seketika (ICC), dan kendala non-holonomik Pfaffian.',
    levelRange: 'Level 3',
    iconName: 'Cpu',
    primaryEmbodiment: 'Mobile & Arms',
  },
  {
    id: 'planning',
    slug: 'planning',
    titleEn: 'Path Planning & Graph Search',
    titleId: 'Perencanaan Jalur & Pencarian Graf',
    descriptionEn: 'Discrete graph search, Dijkstra, A* heuristics, configuration space expansion, and obstacle avoidance.',
    descriptionId: 'Pencarian graf diskrit, Dijkstra, heuristik A*, ekspansi ruang konfigurasi, dan penghindaran rintangan.',
    levelRange: 'Level 6',
    iconName: 'Navigation',
    primaryEmbodiment: 'Mobile, Arms, Aerial',
  },
  {
    id: 'control',
    slug: 'control',
    titleEn: 'Dynamics & Control',
    titleId: 'Dinamika & Kendali',
    descriptionEn: 'Pure Pursuit geometric steering, Stanley cross-track error feedback, PID loops, and trajectory tracking.',
    descriptionId: 'Kemudi geometris Pure Pursuit, umpan balik lateral Stanley, loop PID, dan pelacakan trajektori.',
    levelRange: 'Level 7',
    iconName: 'Activity',
    primaryEmbodiment: 'Mobile, Aerial, Legged',
  },
  {
    id: 'sensors',
    slug: 'sensors',
    titleEn: 'Sensors & Hardware Perception',
    titleId: 'Sensor & Persepsi Perangkat Keras',
    descriptionEn: 'Optical encoders, IMU, ultrasonic rangefinders, LiDAR measurement models, and Gaussian sensor noise.',
    descriptionId: 'Enkoder optik, IMU, sonar ultrasonik, model pengukuran LiDAR, dan derau sensor Gaussian.',
    levelRange: 'Level 5',
    iconName: 'Activity',
    primaryEmbodiment: 'All Embodiments',
  },
  {
    id: 'estimation',
    slug: 'estimation',
    titleEn: 'State Estimation & Localization',
    titleId: 'Estimasi Status & Lokalisasi',
    descriptionEn: 'Recursive Bayesian filtering, Monte Carlo Localization (MCL) Particle Filters, and sensor fusion.',
    descriptionId: 'Filter Bayesian rekursif, Filter Partikel Monte Carlo Localization (MCL), dan fusi sensor.',
    levelRange: 'Level 8',
    iconName: 'MapPin',
    primaryEmbodiment: 'Mobile, Marine, Aerial',
  },
  {
    id: 'perception',
    slug: 'perception',
    titleEn: 'Mapping & Spatial Occupancy',
    titleId: 'Pemetaan & Okupansi Spasial',
    descriptionEn: '360° LiDAR raycasting, Gaussian measurement noise models, and Log-Odds Bayesian Occupancy Grid Mapping.',
    descriptionId: 'Raycasting LiDAR 360°, model derau Gaussian, dan Pemetaan Grid Okupansi Log-Odds Bayesian.',
    levelRange: 'Level 9',
    iconName: 'Layers',
    primaryEmbodiment: 'Mobile & Aerial',
  },
  {
    id: 'manipulation',
    slug: 'manipulation',
    titleEn: 'Manipulation & Serial Arms',
    titleId: 'Manipulasi & Lengan Serial',
    descriptionEn: 'Forward and inverse kinematics, Denavit-Hartenberg parameters, Jacobians, and workspace reachability.',
    descriptionId: 'Kinematika maju dan invers, parameter Denavit-Hartenberg, Jacobian, dan keterjangkauan ruang kerja.',
    levelRange: 'Level 14',
    iconName: 'Cpu',
    primaryEmbodiment: 'Manipulator Arms',
  },
  {
    id: 'advanced',
    slug: 'advanced',
    titleEn: 'Advanced Systems & Swarm Intelligence',
    titleId: 'Sistem Lanjutan & Kecerdasan Kawanan',
    descriptionEn: 'Iterative Closest Point (ICP) SLAM, Graph Laplacian consensus dynamics, and decentralized multi-agent swarms.',
    descriptionId: 'SLAM Iterative Closest Point (ICP), dinamika konsensus Graf Laplacian, dan kawanan multi-agent.',
    levelRange: 'Levels 10 & 18',
    iconName: 'Users',
    primaryEmbodiment: 'Swarms & Frontier Robots',
  },
];

export const LESSON_REGISTRY: LessonRegistryItem[] = [
  {
    id: 'intro-to-robotics',
    slug: 'intro-to-robotics',
    domain: 'fundamentals',
    level: 0,
    tier: 'Foundations',
    titleEn: 'Introduction to Autonomous Robotics & Classifications',
    titleId: 'Pengantar Robotika Otonom & Klasifikasinya',
    difficulty: 'Beginner',
    estimatedMinutes: 30,
    prerequisites: [],
    platforms: ['mobile', 'manipulator', 'aerial', 'marine', 'legged'],
    components: ['SensePlanActExplorer', 'RobotClassificationExplorer', 'ConceptCheck'],
    interactive: true,
    references: ['Elements of Robotics (Ben-Ari & Mondada)', 'Foundations of Robotics (Herath & St-Onge)'],
  },
  {
    id: 'aerial-drone-principles',
    slug: 'aerial-drone-principles',
    domain: 'fundamentals',
    level: 0,
    tier: 'Foundations',
    titleEn: 'Aerial Robotics: Multirotor Flight Dynamics & 6-DOF Thrust Control',
    titleId: 'Robotika Udara: Dinamika Penerbangan Multirotor & Kendali Dorong 6-DOF',
    difficulty: 'Beginner',
    estimatedMinutes: 40,
    prerequisites: ['intro-to-robotics'],
    platforms: ['aerial'],
    components: ['QuadrotorDynamicsSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Quadrotor Dynamics and Control (Beard)', 'Introduction to Multicopter Design and Control (Quan)'],
  },
  {
    id: 'marine-robotics-fundamentals',
    slug: 'marine-robotics-fundamentals',
    domain: 'fundamentals',
    level: 0,
    tier: 'Foundations',
    titleEn: 'Marine Robotics: Hydrodynamics, Buoyancy & 6-DOF AUV Equations',
    titleId: 'Robotika Laut: Hidrodinamika, Gaya Apung & Persamaan AUV 6-DOF',
    difficulty: 'Beginner',
    estimatedMinutes: 40,
    prerequisites: ['intro-to-robotics'],
    platforms: ['marine'],
    components: ['MarineHydrodynamicsSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Handbook of Marine Craft Hydrodynamics and Motion Control (Fossen)', 'Underwater Robots (Antonelli)'],
  },
  {
    id: 'legged-robotics-fundamentals',
    slug: 'legged-robotics-fundamentals',
    domain: 'fundamentals',
    level: 0,
    tier: 'Foundations',
    titleEn: 'Legged Robotics: Zero Moment Point (ZMP) & Inverted Pendulum Locomotion',
    titleId: 'Robotika Berkaki: Zero Moment Point (ZMP) & Lokomosi Pendulum Terbalik',
    difficulty: 'Beginner',
    estimatedMinutes: 40,
    prerequisites: ['intro-to-robotics'],
    platforms: ['legged'],
    components: ['LeggedZmpSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Introduction to Humanoid Robotics (Kajita et al.)', 'Zero-Moment Point: Thirty Five Years of its Life (Vukobratovic)'],
  },
  {
    id: 'mathematical-foundations',
    slug: 'mathematical-foundations',
    domain: 'mathematics',
    level: 1,
    tier: 'Foundations',
    titleEn: 'Mathematical & Geometric Foundations for Robotics',
    titleId: 'Fundamental Matematika & Geometri untuk Robotika',
    difficulty: 'Beginner',
    estimatedMinutes: 45,
    prerequisites: ['intro-to-robotics'],
    platforms: ['manipulator', 'mobile', 'aerial', 'marine', 'legged'],
    components: ['CoordinateFrameExplorer', 'VectorVisualizer', 'DotProductExplorer', 'ConceptCheck'],
    interactive: true,
    references: ['Elements of Robotics', 'Foundations of Robotics', 'Planning Algorithms'],
  },
  {
    id: 'vectors-and-coordinate-geometry',
    slug: 'vectors-and-coordinate-geometry',
    domain: 'mathematics',
    level: 1,
    tier: 'Foundations',
    titleEn: 'Vectors, Coordinate Geometry & Euclidean Metrics (M01)',
    titleId: 'Vektor, Geometri Koordinat & Metrik Euclidean (M01)',
    difficulty: 'Beginner',
    estimatedMinutes: 35,
    prerequisites: ['intro-to-robotics'],
    platforms: ['mobile', 'manipulator', 'aerial', 'marine', 'legged'],
    components: ['VectorVisualizer', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Elements of Robotics (Chapter 2)', 'Introduction to Linear Algebra (Strang)'],
  },
  {
    id: 'dot-product-and-projection',
    slug: 'dot-product-and-projection',
    domain: 'mathematics',
    level: 1,
    tier: 'Foundations',
    titleEn: 'Dot Product, Orthogonality & Vector Projection (M02)',
    titleId: 'Dot Product, Ortogonalitas & Proyeksi Vektor (M02)',
    difficulty: 'Beginner',
    estimatedMinutes: 40,
    prerequisites: ['vectors-and-coordinate-geometry'],
    platforms: ['mobile', 'manipulator', 'aerial', 'marine', 'legged'],
    components: ['DotProductExplorer', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Introduction to Linear Algebra (Strang)', 'Foundations of Robotics (Chapter 2)'],
  },
  {
    id: 'probability-for-robotics',
    slug: 'probability-for-robotics',
    domain: 'mathematics',
    level: 1,
    tier: 'Foundations',
    titleEn: 'Probability Theory & Bayesian Reasoning for Robotics (M10)',
    titleId: 'Teori Probabilitas & Penalaran Bayesian untuk Robotika (M10)',
    difficulty: 'Beginner',
    estimatedMinutes: 40,
    prerequisites: ['vectors-and-coordinate-geometry'],
    platforms: ['mobile', 'manipulator', 'aerial', 'marine', 'legged'],
    components: ['BayesianRoomSimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Probabilistic Robotics (Thrun et al., Chapter 2)', 'Introduction to Probability Models (Ross)'],
  },
  {
    id: 'numerical-stability-euler-vs-rk4',
    slug: 'numerical-stability-euler-vs-rk4',
    domain: 'mathematics',
    level: 1,
    tier: 'Foundations',
    titleEn: 'Numerical Stability & Integration: Euler vs Symplectic vs RK4 (M29)',
    titleId: 'Stabilitas Numerik & Integrasi: Euler vs Simplektik vs RK4 (M29)',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['mathematical-foundations'],
    platforms: ['mobile', 'manipulator', 'aerial', 'marine', 'legged'],
    components: ['NumericalIntegrationSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Hairer, Norsett, Wanner (1993). Solving Ordinary Differential Equations I: Nonstiff Problems. Springer.', 'Underactuated Robotics (Tedrake)'],
  },
  {
    id: '2d-geometry',
    slug: '2d-geometry',
    domain: 'geometry',
    level: 2,
    tier: 'Foundations',
    titleEn: '2D Planar Geometry & Homogeneous Transforms SE(2)',
    titleId: 'Geometri Planar 2D & Transformasi Homogen SE(2)',
    difficulty: 'Beginner',
    estimatedMinutes: 35,
    prerequisites: ['mathematical-foundations'],
    platforms: ['mobile', 'manipulator'],
    components: ['TransformSandbox', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Foundations of Robotics (Chapter 2)'],
  },
  {
    id: 'lie-groups-and-lie-algebras',
    slug: 'lie-groups-and-lie-algebras',
    domain: 'geometry',
    level: 2,
    tier: 'Foundations',
    titleEn: 'Matrix Lie Groups SO(3)/SE(3) & Lie Algebras so(3)/se(3)',
    titleId: 'Grup Lie Matriks SO(3)/SE(3) & Aljabar Lie so(3)/se(3)',
    difficulty: 'Advanced',
    estimatedMinutes: 45,
    prerequisites: ['2d-rotation-matrices', '3d-geometry'],
    platforms: ['mobile', 'manipulator', 'aerial', 'marine', 'legged'],
    components: ['LieGroupAlgebraSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['A Micro Lie Theory for State Estimation in Robotics (Solà)', 'State Estimation for Robotics (Barfoot)'],
  },
  {
    id: '2d-rotation-matrices',
    slug: '2d-rotation-matrices',
    domain: 'geometry',
    level: 2,
    tier: 'Foundations',
    titleEn: '2D Spatial Rotation & Special Orthogonal Group SO(2) (M03)',
    titleId: 'Rotasi Spasial 2D & Grup Ortogonal Khusus SO(2) (M03)',
    difficulty: 'Intermediate',
    estimatedMinutes: 40,
    prerequisites: ['vectors-and-coordinate-geometry', 'dot-product-and-projection'],
    platforms: ['mobile', 'manipulator', 'aerial', 'marine', 'legged'],
    components: ['SpatialRotation2D', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Foundations of Robotics (Chapter 2)', 'Modern Robotics (Lynch & Park)'],
  },
  {
    id: 'coordinate-frames-and-transforms',
    slug: 'coordinate-frames-and-transforms',
    domain: 'geometry',
    level: 2,
    tier: 'Foundations',
    titleEn: 'Coordinate Frames, SE(2) Transforms & Frame Trees (M04)',
    titleId: 'Kerangka Koordinat, Transformasi SE(2) & Pohon Transformasi (M04)',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['vectors-and-coordinate-geometry', '2d-rotation-matrices'],
    platforms: ['mobile', 'manipulator', 'aerial', 'marine', 'legged'],
    components: ['CoordinateFrameExplorer', 'TransformSandbox', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Foundations of Robotics (Chapter 2)', 'Introduction to Robotics (Craig)'],
  },
  {
    id: 'transform-composition-and-chains',
    slug: 'transform-composition-and-chains',
    domain: 'geometry',
    level: 2,
    tier: 'Foundations',
    titleEn: 'Transform Composition, Matrix Non-Commutativity & Kinematic Chains (M05)',
    titleId: 'Komposisi Transformasi, Sifat Non-Komutatif & Rantai Kinematik (M05)',
    difficulty: 'Intermediate',
    estimatedMinutes: 40,
    prerequisites: ['coordinate-frames-and-transforms', '2d-rotation-matrices'],
    platforms: ['mobile', 'manipulator', 'aerial', 'marine', 'legged'],
    components: ['TransformChainSimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Introduction to Robotics (Craig, Chapter 2)', 'Foundations of Robotics (Chapter 2)'],
  },
  {
    id: '3d-geometry',
    slug: '3d-geometry',
    domain: 'geometry',
    level: 2,
    tier: 'Foundations',
    titleEn: '3D Spatial Geometry, Euler Angles & SO(3) Rotations',
    titleId: 'Geometri Spasial 3D, Sudut Euler & Rotasi SO(3)',
    difficulty: 'Intermediate',
    estimatedMinutes: 40,
    prerequisites: ['2d-geometry'],
    platforms: ['manipulator', 'aerial', 'marine', 'legged'],
    components: ['SpatialRotation3D', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Foundations of Robotics (Chapter 3)'],
  },
  {
    id: 'configuration-space-and-minkowski',
    slug: 'configuration-space-and-minkowski',
    domain: 'geometry',
    level: 2,
    tier: 'Foundations',
    titleEn: 'Configuration Space (C-Space) & Minkowski Sum Obstacle Inflation',
    titleId: 'Ruang Konfigurasi (C-Space) & Inflasi Rintangan Minkowski Sum',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['2d-geometry', 'mathematical-foundations'],
    platforms: ['mobile', 'manipulator', 'aerial'],
    components: ['CspaceInflationSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Planning Algorithms (Chapter 4)', 'Spatial Planning: A Configuration Space Approach (Lozano-Perez)'],
  },
  {
    id: 'velocity-kinematics-2d',
    slug: 'velocity-kinematics-2d',
    domain: 'kinematics',
    level: 3,
    tier: 'Foundations',
    titleEn: '2D Velocity Kinematics & Differential Drive Unicycle',
    titleId: 'Kinematika Kecepatan 2D & Unicycle Roda Diferensial',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['2d-geometry'],
    platforms: ['mobile'],
    components: ['KinematicsSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Elements of Robotics (Chapter 5)'],
  },
  {
    id: 'differential-drive-kinematics',
    slug: 'differential-drive-kinematics',
    domain: 'kinematics',
    level: 3,
    tier: 'Foundations',
    titleEn: 'Differential Drive Kinematics & Instantaneous Center of Curvature (M06)',
    titleId: 'Kinematika Roda Diferensial & Pusat Kurvatur Seketika ICC (M06)',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['vectors-and-coordinate-geometry', '2d-rotation-matrices'],
    platforms: ['mobile'],
    components: ['KinematicsSimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Elements of Robotics (Chapter 5)', 'Introduction to Autonomous Mobile Robots (Siegwart)'],
  },
  {
    id: 'non-holonomic-constraints',
    slug: 'non-holonomic-constraints',
    domain: 'kinematics',
    level: 3,
    tier: 'Foundations',
    titleEn: 'Non-Holonomic Motion Constraints & Pfaffian Forms (M07)',
    titleId: 'Kendala Gerak Non-Holonomik & Bentuk Pfaffian (M07)',
    difficulty: 'Advanced',
    estimatedMinutes: 45,
    prerequisites: ['differential-drive-kinematics', '2d-rotation-matrices'],
    platforms: ['mobile', 'aerial'],
    components: ['HolonomicConstraintSimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Planning Algorithms (LaValle, Chapter 13)', 'Modern Robotics (Lynch & Park, Chapter 13)'],
  },
  {
    id: 'sensor-fundamentals',
    slug: 'sensor-fundamentals',
    domain: 'sensors',
    level: 5,
    tier: 'Core Autonomy',
    titleEn: 'Sensor Fundamentals, Measurement Models & Gaussian Noise',
    titleId: 'Fundamental Sensor, Model Pengukuran & Derau Gaussian',
    difficulty: 'Beginner',
    estimatedMinutes: 35,
    prerequisites: ['mathematical-foundations'],
    platforms: ['mobile', 'manipulator', 'aerial', 'marine', 'legged'],
    components: ['SensorNoiseSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Elements of Robotics (Chapter 4)', 'Foundations of Robotics (Chapter 5)'],
  },
  {
    id: 'sensor-noise-and-uncertainty',
    slug: 'sensor-noise-and-uncertainty',
    domain: 'sensors',
    level: 5,
    tier: 'Core Autonomy',
    titleEn: 'Sensor Noise Models, Gaussian Uncertainty & Probability Density (M08)',
    titleId: 'Model Derau Sensor, Ketidakpastian Gaussian & Kerapatan Probabilitas (M08)',
    difficulty: 'Beginner',
    estimatedMinutes: 40,
    prerequisites: ['vectors-and-coordinate-geometry', 'sensor-fundamentals'],
    platforms: ['mobile', 'manipulator', 'aerial', 'marine', 'legged'],
    components: ['SensorNoiseSimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Probabilistic Robotics (Chapter 2 & 6)', 'Elements of Robotics (Chapter 4)'],
  },
  {
    id: 'wheel-odometry-and-drift',
    slug: 'wheel-odometry-and-drift',
    domain: 'sensors',
    level: 5,
    tier: 'Core Autonomy',
    titleEn: 'Wheel Odometry, Encoder Dead Reckoning & Systematic Drift',
    titleId: 'Odometri Roda, Dead Reckoning Enkoder & Akumulasi Drift',
    difficulty: 'Intermediate',
    estimatedMinutes: 40,
    prerequisites: ['velocity-kinematics-2d', 'sensor-fundamentals'],
    platforms: ['mobile'],
    components: ['OdometryDriftSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Elements of Robotics (Chapter 5)', 'Measurement and Correction of Systematic Odometry Errors in Mobile Robots (Borenstein & Feng)'],
  },
  {
    id: 'lidar-raycasting',
    slug: 'lidar-raycasting',
    domain: 'sensors',
    level: 5,
    tier: 'Core Autonomy',
    titleEn: 'LiDAR Raycasting, Beam Intersection & Point Cloud Extraction (M21)',
    titleId: 'Raycasting LiDAR, Pemotongan Sinar & Ekstraksi Point Cloud (M21)',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['2d-geometry', 'sensor-fundamentals'],
    platforms: ['mobile', 'aerial', 'marine', 'legged'],
    components: ['LidarRaycastSimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Probabilistic Robotics (Chapter 6)', 'Introduction to Autonomous Mobile Robots (Chapter 4)'],
  },
  {
    id: 'a-star',
    slug: 'a-star',
    domain: 'planning',
    level: 6,
    tier: 'Core Autonomy',
    titleEn: 'A* Grid Search & Admissible Heuristics',
    titleId: 'Pencarian Grid A* & Heuristik Admisibel',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['velocity-kinematics-2d'],
    platforms: ['mobile', 'manipulator'],
    components: ['PathPlanningSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Planning Algorithms (LaValle, Chapter 2)'],
  },
  {
    id: 'astar-vs-dijkstra-search',
    slug: 'astar-vs-dijkstra-search',
    domain: 'planning',
    level: 6,
    tier: 'Core Autonomy',
    titleEn: 'A* vs. Dijkstra Search: Heuristics & Exploration Wavefronts (M15)',
    titleId: 'Komparasi Pencarian Jalur: A* vs. Dijkstra & Heuristik (M15)',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['a-star', 'vectors-and-coordinate-geometry'],
    platforms: ['mobile', 'manipulator'],
    components: ['AStarVsDijkstraSimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['A Formal Basis for the Heuristic Determination of Minimum Cost Paths (Hart et al.)', 'Planning Algorithms (LaValle, Chapter 2)'],
  },
  {
    id: 'rrt-and-rrt-star',
    slug: 'rrt-and-rrt-star',
    domain: 'planning',
    level: 6,
    tier: 'Core Autonomy',
    titleEn: 'Sampling-Based Motion Planning: RRT & RRT*',
    titleId: 'Perencanaan Gerak Berbasis Sampel: RRT & RRT*',
    difficulty: 'Advanced',
    estimatedMinutes: 45,
    prerequisites: ['2d-geometry', 'a-star'],
    platforms: ['mobile', 'manipulator', 'aerial'],
    components: ['RrtSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Planning Algorithms (Chapter 5)', 'Sampling-based Algorithms for Optimal Motion Planning (Karaman & Frazzoli)'],
  },
  {
    id: 'rrt-sampling-planner',
    slug: 'rrt-sampling-planner',
    domain: 'planning',
    level: 6,
    tier: 'Core Autonomy',
    titleEn: 'Rapidly-exploring Random Trees: RRT & RRT* Motion Planning (M17)',
    titleId: 'Rapidly-exploring Random Trees: Perencanaan Gerak RRT & RRT* (M17)',
    difficulty: 'Advanced',
    estimatedMinutes: 45,
    prerequisites: ['configuration-space-and-minkowski', 'a-star'],
    platforms: ['mobile', 'manipulator', 'aerial'],
    components: ['RrtExplorationSimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Rapidly-Exploring Random Trees (LaValle)', 'Sampling-based Algorithms for Optimal Motion Planning (Karaman & Frazzoli)'],
  },
  {
    id: 'autonomous-exploration-lags',
    slug: 'autonomous-exploration-lags',
    domain: 'planning',
    level: 6,
    tier: 'Core Autonomy',
    titleEn: 'Information-Theoretic Autonomous Exploration & Local-Global Strategy (LAGS)',
    titleId: 'Eksplorasi Otonom Berbasis Informasi & Strategi Lokal-Global (LAGS / MDPI 2023)',
    difficulty: 'Advanced',
    estimatedMinutes: 45,
    prerequisites: ['a-star', 'occupancy-grid-mapping', 'probability-for-robotics'],
    platforms: ['mobile', 'aerial'],
    components: ['AutonomousExplorationSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Efficient Autonomous Exploration and Mapping in Unknown Environments (Feng et al., Sensors 2023)', 'On Mutual Information-Based Control of Range Sensing Robots (Julian et al.)'],
  },
  {
    id: '3d-frontier-exploration-mav',
    slug: '3d-frontier-exploration-mav',
    domain: 'planning',
    level: 6,
    tier: 'Core Autonomy',
    titleEn: '3D Frontier-Based Autonomous Exploration & Safe Flight Corridors',
    titleId: 'Eksplorasi Frontier 3D & Safe Flight Corridor MAV (MDPI 2020)',
    difficulty: 'Advanced',
    estimatedMinutes: 45,
    prerequisites: ['a-star', 'autonomous-exploration-lags', '3d-lidar-and-vslam'],
    platforms: ['aerial', 'mobile'],
    components: ['SafeCorridorExplorationSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Optimal Frontier-Based Autonomous Exploration in Unconstructed Environment Using RGB-D Sensor (Lu et al., Sensors 2020)', 'OctoMap: An Efficient Probabilistic 3D Mapping Framework Based on Octrees (Hornung et al.)'],
  },
  {
    id: 'path-tracking-error-geometry',
    slug: 'path-tracking-error-geometry',
    domain: 'control',
    level: 7,
    tier: 'Core Autonomy',
    titleEn: 'Path Tracking Error Geometry: Cross-Track & Heading Errors (M14)',
    titleId: 'Geometri Galat Pelacakan Jalur: Galat Cross-Track & Heading (M14)',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['dot-product-and-projection', '2d-rotation-matrices'],
    platforms: ['mobile', 'aerial'],
    components: ['TrackingErrorGeometrySimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Autonomous Automobile Trajectory Tracking (Hoffmann et al.)', 'Introduction to Autonomous Mobile Robots (Siegwart)'],
  },
  {
    id: 'pure-pursuit-path-tracking',
    slug: 'pure-pursuit-path-tracking',
    domain: 'control',
    level: 7,
    tier: 'Core Autonomy',
    titleEn: 'Pure Pursuit Geometric Path Tracking Control (M13)',
    titleId: 'Kendali Pelacakan Jalur Geometris Pure Pursuit (M13)',
    difficulty: 'Intermediate',
    estimatedMinutes: 40,
    prerequisites: ['path-tracking-error-geometry', 'differential-drive-kinematics'],
    platforms: ['mobile', 'aerial'],
    components: ['PurePursuitSimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Implementation of the Pure Pursuit Path Tracking Algorithm (Coulter)', 'Introduction to Autonomous Mobile Robots (Siegwart)'],
  },
  {
    id: 'pure-pursuit-and-stanley',
    slug: 'pure-pursuit-and-stanley',
    domain: 'control',
    level: 7,
    tier: 'Core Autonomy',
    titleEn: 'Pure Pursuit & Stanley Trajectory Tracking Control',
    titleId: 'Kendali Pelacakan Trajektori Pure Pursuit & Stanley',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['velocity-kinematics-2d', 'a-star'],
    platforms: ['mobile', 'aerial'],
    components: ['ControlSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Foundations of Robotics (Chapter 6)'],
  },
  {
    id: 'pid-and-lqr-control',
    slug: 'pid-and-lqr-control',
    domain: 'control',
    level: 7,
    tier: 'Core Autonomy',
    titleEn: 'PID Feedback Control & State-Space Optimal Regulation',
    titleId: 'Kendali Umpan Balik PID & Regulasi Ruang Status Optimal',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['mathematical-foundations', 'velocity-kinematics-2d'],
    platforms: ['mobile', 'aerial', 'manipulator', 'legged'],
    components: ['PidTuningSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Feedback Systems: An Introduction for Scientists and Engineers (Astrom & Murray)'],
  },
  {
    id: 'state-space-and-feedback',
    slug: 'state-space-and-feedback',
    domain: 'control',
    level: 7,
    tier: 'Core Autonomy',
    titleEn: 'State-Space Representation, Phase Portraits & Full-State Feedback (M27)',
    titleId: 'Representasi Ruang Status, Diagram Fase & Umpan Balik Status Penuh (M27)',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['pid-and-lqr-control', 'vectors-and-coordinate-geometry'],
    platforms: ['mobile', 'aerial', 'manipulator', 'legged'],
    components: ['StateSpaceSimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Feedback Systems: An Introduction for Scientists and Engineers (Astrom & Murray)', 'Modern Control Engineering (Ogata)'],
  },
  {
    id: 'discrete-time-simulation',
    slug: 'discrete-time-simulation',
    domain: 'control',
    level: 7,
    tier: 'Core Autonomy',
    titleEn: 'Discrete-Time Numerical Simulation: Euler, RK4 & Stability (M28)',
    titleId: 'Simulasi Numerik Waktu Diskret: Euler, RK4 & Batas Stabilitas (M28)',
    difficulty: 'Intermediate',
    estimatedMinutes: 40,
    prerequisites: ['mathematical-foundations', 'differential-drive-kinematics'],
    platforms: ['mobile', 'aerial', 'manipulator', 'legged', 'marine'],
    components: ['NumericalDiscretizationSimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Numerical Recipes: The Art of Scientific Computing (Press et al.)', 'Modern Robotics (Lynch & Park)'],
  },
  {
    id: 'bayes-filter-and-kalman',
    slug: 'bayes-filter-and-kalman',
    domain: 'estimation',
    level: 8,
    tier: 'Core Autonomy',
    titleEn: 'Recursive Bayesian Filtering & 1D Kalman Filter State Estimation',
    titleId: 'Filter Bayesian Rekursif & Estimasi Status Filter Kalman 1D',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['mathematical-foundations', 'sensor-fundamentals'],
    platforms: ['mobile', 'marine', 'aerial', 'manipulator'],
    components: ['BayesianFilterSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Probabilistic Robotics (Thrun et al., Chapter 2 & 3)', 'A New Approach to Linear Filtering and Prediction Problems (Kalman)'],
  },
  {
    id: 'localization-fundamentals',
    slug: 'localization-fundamentals',
    domain: 'estimation',
    level: 8,
    tier: 'Core Autonomy',
    titleEn: 'Mobile Robot Localization Fundamentals & Prerequisites',
    titleId: 'Prinsip Dasar Lokalisasi Robot Mobile & Prasyarat Keilmuan',
    difficulty: 'Beginner',
    estimatedMinutes: 35,
    prerequisites: ['differential-drive-kinematics', 'lidar-raycasting', 'bayes-filter-and-kalman'],
    platforms: ['mobile', 'aerial', 'marine'],
    components: ['LocalizationSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Probabilistic Robotics (Thrun et al., Chapter 7)', 'Introduction to Autonomous Mobile Robots (Siegwart)'],
  },
  {
    id: 'ekf-localization',
    slug: 'ekf-localization',
    domain: 'estimation',
    level: 8,
    tier: 'Core Autonomy',
    titleEn: 'Extended Kalman Filter (EKF) Non-Linear 2D Localization',
    titleId: 'Lokalisasi 2D Non-Linear Extended Kalman Filter (EKF)',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['bayes-filter-and-kalman', 'localization-fundamentals'],
    platforms: ['mobile', 'aerial', 'marine'],
    components: ['EkfLocalizationSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Probabilistic Robotics (Thrun et al., Chapter 7)', 'PythonRobotics (Atsushi Sakai)'],
  },
  {
    id: 'sensor-fusion-imu-gps-odometry',
    slug: 'sensor-fusion-imu-gps-odometry',
    domain: 'estimation',
    level: 8,
    tier: 'Core Autonomy',
    titleEn: 'Multi-Sensor Fusion: Wheel Odometry + IMU + GPS (M30)',
    titleId: 'Fusi Multi-Sensor: Odometri Roda + IMU + GPS (M30)',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['ekf-localization', 'sensor-noise-and-uncertainty'],
    platforms: ['mobile', 'aerial', 'marine', 'legged'],
    components: ['SensorFusionSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Farrell (2008). Aided Navigation: GPS with High Rate Sensors. McGraw-Hill.', 'Probabilistic Robotics (Thrun et al.)'],
  },
  {
    id: 'histogram-filter-localization',
    slug: 'histogram-filter-localization',
    domain: 'estimation',
    level: 8,
    tier: 'Core Autonomy',
    titleEn: 'Histogram Filter / Discrete Grid-Based Topological Localization',
    titleId: 'Lokalisasi Grid Diskret & Filter Histogram Topologis',
    difficulty: 'Intermediate',
    estimatedMinutes: 40,
    prerequisites: ['localization-fundamentals', 'probability-for-robotics'],
    platforms: ['mobile', 'aerial'],
    components: ['HistogramFilterSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Probabilistic Robotics (Thrun et al., Chapter 7)', 'Artificial Intelligence: A Modern Approach (Russell & Norvig)'],
  },
  {
    id: 'mcl-particle-filter',
    slug: 'mcl-particle-filter',
    domain: 'estimation',
    level: 8,
    tier: 'Core Autonomy',
    titleEn: 'Monte Carlo Localization (MCL) Particle Filters',
    titleId: 'Filter Partikel Monte Carlo Localization (MCL)',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['mathematical-foundations', 'velocity-kinematics-2d'],
    platforms: ['mobile', 'marine', 'aerial'],
    components: ['LocalizationSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Probabilistic Robotics (Thrun et al., Chapter 8)'],
  },
  {
    id: 'occupancy-grid-mapping',
    slug: 'occupancy-grid-mapping',
    domain: 'perception',
    level: 9,
    tier: 'Spatial Intelligence',
    titleEn: 'Log-Odds Bayesian Occupancy Grid Mapping',
    titleId: 'Pemetaan Grid Okupansi Log-Odds Bayesian',
    difficulty: 'Intermediate',
    estimatedMinutes: 40,
    prerequisites: ['mathematical-foundations', 'velocity-kinematics-2d'],
    platforms: ['mobile', 'aerial'],
    components: ['MappingSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Probabilistic Robotics (Thrun et al., Chapter 9)'],
  },
  {
    id: 'gaussian-grid-map',
    slug: 'gaussian-grid-map',
    domain: 'perception',
    level: 9,
    tier: 'Spatial Intelligence',
    titleEn: 'Gaussian Grid Mapping & Kernel Density Estimation',
    titleId: 'Pemetaan Grid Gaussian & Estimasi Kerapatan Kernel',
    difficulty: 'Intermediate',
    estimatedMinutes: 40,
    prerequisites: ['sensor-noise-and-uncertainty', 'occupancy-grid-mapping'],
    platforms: ['mobile', 'aerial', 'marine'],
    components: ['GaussianGridMapSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Probabilistic Robotics (Thrun et al.)', 'PythonRobotics (Atsushi Sakai)'],
  },
  {
    id: 'raycasting-grid-map',
    slug: 'raycasting-grid-map',
    domain: 'perception',
    level: 9,
    tier: 'Spatial Intelligence',
    titleEn: 'Ray Casting Grid Map & Bresenham Line Traversal',
    titleId: 'Pemetaan Grid Raycasting & Penelusuran Garis Bresenham',
    difficulty: 'Intermediate',
    estimatedMinutes: 40,
    prerequisites: ['occupancy-grid-mapping', 'lidar-raycasting'],
    platforms: ['mobile', 'aerial'],
    components: ['RayCastingGridMapSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Algorithm for Computer Control of a Digital Plotter (Bresenham)', 'PythonRobotics (Atsushi Sakai)'],
  },
  {
    id: 'lidar-to-grid-map',
    slug: 'lidar-to-grid-map',
    domain: 'perception',
    level: 5,
    tier: 'Core Autonomy',
    titleEn: 'LiDAR to Grid Map Polar-to-Cartesian Conversion',
    titleId: 'Konversi Data LiDAR Polar ke Grid Peta Kartesius',
    difficulty: 'Beginner',
    estimatedMinutes: 35,
    prerequisites: ['lidar-raycasting', 'coordinate-frames-and-transforms'],
    platforms: ['mobile', 'aerial', 'marine'],
    components: ['LidarToGridMapSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Introduction to Autonomous Mobile Robots (Siegwart)', 'PythonRobotics (Atsushi Sakai)'],
  },
  {
    id: 'kmeans-object-clustering',
    slug: 'kmeans-object-clustering',
    domain: 'perception',
    level: 9,
    tier: 'Spatial Intelligence',
    titleEn: 'k-Means Point Cloud Obstacle Object Clustering',
    titleId: 'Klasterisasi Objek Rintangan Point Cloud k-Means',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['lidar-to-grid-map', 'vectors-and-coordinate-geometry'],
    platforms: ['mobile', 'aerial', 'manipulator'],
    components: ['KMeansClusteringSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Some Methods for Classification and Analysis of Multivariate Observations (MacQueen)', 'PythonRobotics (Atsushi Sakai)'],
  },
  {
    id: 'rectangle-fitting',
    slug: 'rectangle-fitting',
    domain: 'perception',
    level: 9,
    tier: 'Spatial Intelligence',
    titleEn: 'Oriented Rectangle (OBB) & L-Shape Bounding Box Fitting',
    titleId: 'Oriented Bounding Box (OBB) & Fitting Kotak Pembatas Bentuk-L',
    difficulty: 'Advanced',
    estimatedMinutes: 45,
    prerequisites: ['kmeans-object-clustering', '2d-rotation-matrices'],
    platforms: ['mobile', 'aerial'],
    components: ['RectangleFittingSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Efficient L-Shape Fitting for Vehicle Detection Using Laser Scanners (Zhang et al.)', 'PythonRobotics (Atsushi Sakai)'],
  },
  {
    id: '2dof-forward-kinematics',
    slug: '2dof-forward-kinematics',
    domain: 'manipulation',
    level: 14,
    tier: 'Advanced Embodiments',
    titleEn: '2-DOF Planar Arm Forward Kinematics & Workspace Sweep (M18)',
    titleId: 'Kinematika Maju Lengan Robot 2-DOF & Batas Ruang Kerja (M18)',
    difficulty: 'Beginner',
    estimatedMinutes: 40,
    prerequisites: ['2d-rotation-matrices', 'transform-composition-and-chains'],
    platforms: ['manipulator'],
    components: ['ArmForwardKinematicsSimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Introduction to Robotics: Mechanics and Control (Craig, Chapter 3)', 'Modern Robotics (Lynch & Park, Chapter 4)'],
  },
  {
    id: '2dof-inverse-kinematics',
    slug: '2dof-inverse-kinematics',
    domain: 'manipulation',
    level: 14,
    tier: 'Advanced Embodiments',
    titleEn: '2-DOF Planar Arm Analytical Inverse Kinematics (M19)',
    titleId: 'Kinematika Invers Analitik Lengan Robot 2-DOF (M19)',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['2dof-forward-kinematics', 'dot-product-and-projection'],
    platforms: ['manipulator'],
    components: ['ArmInverseKinematicsSimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Introduction to Robotics: Mechanics and Control (Craig, Chapter 4)', 'Modern Robotics (Lynch & Park, Chapter 6)'],
  },
  {
    id: 'jacobian-and-singularity',
    slug: 'jacobian-and-singularity',
    domain: 'manipulation',
    level: 14,
    tier: 'Advanced Embodiments',
    titleEn: 'Manipulator Jacobian, Velocity Ellipsoids & Kinematic Singularities (M20)',
    titleId: 'Matriks Jacobian, Elips Manipulabilitas & Singularitas Kinematik (M20)',
    difficulty: 'Advanced',
    estimatedMinutes: 50,
    prerequisites: ['2dof-forward-kinematics', '2dof-inverse-kinematics'],
    platforms: ['manipulator'],
    components: ['JacobianSingularitySimulator', 'VideoEmbed', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Introduction to Robotics: Mechanics and Control (Craig, Chapter 5)', 'Modern Robotics (Lynch & Park, Chapter 5)'],
  },
  {
    id: 'forward-inverse-kinematics',
    slug: 'forward-inverse-kinematics',
    domain: 'manipulation',
    level: 14,
    tier: 'Advanced Embodiments',
    titleEn: 'Serial Manipulator Kinematics & Analytical Inverse Kinematics',
    titleId: 'Kinematika Manipulator Serial & Kinematika Invers Analitik',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['2d-geometry', 'mathematical-foundations'],
    platforms: ['manipulator'],
    components: ['ArmKinematicsSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Foundations of Robotics (Chapter 4)', 'Introduction to Robotics: Mechanics and Control (Craig)'],
  },
  {
    id: 'icp-scan-matching',
    slug: 'icp-scan-matching',
    domain: 'advanced',
    level: 10,
    tier: 'Spatial Intelligence',
    titleEn: 'Iterative Closest Point (ICP) Scan Matching in SLAM',
    titleId: 'Pencocokan Pindaian ICP dalam SLAM',
    difficulty: 'Advanced',
    estimatedMinutes: 45,
    prerequisites: ['2d-geometry', 'mathematical-foundations'],
    platforms: ['mobile', 'marine'],
    components: ['SlamSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['A Method for Registration of 3-D Shapes (Besl & McKay)'],
  },
  {
    id: 'slam-fundamentals',
    slug: 'slam-fundamentals',
    domain: 'advanced',
    level: 10,
    tier: 'Spatial Intelligence',
    titleEn: 'Simultaneous Localization & Mapping (SLAM) Foundations & Architecture',
    titleId: 'Prinsip Dasar & Arsitektur Sistem SLAM (MDPI 2025 Review)',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['ekf-localization', 'occupancy-grid-mapping', 'lidar-raycasting'],
    platforms: ['mobile', 'aerial', 'marine'],
    components: ['LoopClosureOptimizationSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['A Review of Simultaneous Localization and Mapping Algorithms Based on Lidar (Li et al., 2025)', 'Probabilistic Robotics (Thrun et al., Chapter 10)'],
  },
  {
    id: 'fastslam-1',
    slug: 'fastslam-1',
    domain: 'advanced',
    level: 10,
    tier: 'Spatial Intelligence',
    titleEn: 'FastSLAM 1.0: Rao-Blackwellized Particle Filtering SLAM',
    titleId: 'FastSLAM 1.0: Pemfilteran Partikel Rao-Blackwellized',
    difficulty: 'Advanced',
    estimatedMinutes: 45,
    prerequisites: ['mcl-particle-filter', 'ekf-localization'],
    platforms: ['mobile', 'aerial', 'marine'],
    components: ['FastSlamSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['FastSLAM: A Factored Solution to the Simultaneous Localization and Mapping Problem (Montemerlo et al.)', 'PythonRobotics (Atsushi Sakai)'],
  },
  {
    id: '2d-lidar-slam',
    slug: '2d-lidar-slam',
    domain: 'advanced',
    level: 10,
    tier: 'Spatial Intelligence',
    titleEn: '2D LiDAR SLAM Paradigms: Gmapping, Hector & Google Cartographer',
    titleId: 'Paradigma SLAM LiDAR 2D: Gmapping, Hector & Google Cartographer',
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    prerequisites: ['slam-fundamentals', 'fastslam-1', 'occupancy-grid-mapping'],
    platforms: ['mobile', 'aerial'],
    components: ['LoopClosureOptimizationSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Real-Time Loop Closure in 2D LIDAR SLAM (Hess et al., Cartographer)', 'Improved Techniques for Grid Mapping with RBPF (Grisetti et al., Gmapping)'],
  },
  {
    id: '3d-lidar-and-vslam',
    slug: '3d-lidar-and-vslam',
    domain: 'advanced',
    level: 10,
    tier: 'Spatial Intelligence',
    titleEn: '3D LiDAR SLAM (LOAM/FAST-LIO) & Visual SLAM (VSLAM)',
    titleId: 'SLAM LiDAR 3D (LOAM/FAST-LIO) & Visual SLAM (VSLAM)',
    difficulty: 'Advanced',
    estimatedMinutes: 50,
    prerequisites: ['slam-fundamentals', 'icp-scan-matching', '2d-lidar-slam'],
    platforms: ['mobile', 'aerial'],
    components: ['SlamSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['LOAM: Lidar Odometry and Mapping in Real-Time (Zhang & Singh)', 'FAST-LIO2: Fast Direct LiDAR-Inertial Odometry (Xu et al.)', 'ORB-SLAM3 (Campos et al.)'],
  },
  {
    id: 'factor-graph-optimization',
    slug: 'factor-graph-optimization',
    domain: 'advanced',
    level: 10,
    tier: 'Spatial Intelligence',
    titleEn: 'Factor Graph Optimization & Non-Linear Least Squares for SLAM',
    titleId: 'Optimasi Graf Faktor & Non-Linear Least Squares untuk SLAM',
    difficulty: 'Advanced',
    estimatedMinutes: 50,
    prerequisites: ['slam-fundamentals', '2d-lidar-slam', 'lie-groups-and-lie-algebras'],
    platforms: ['mobile', 'aerial', 'marine', 'legged'],
    components: ['FactorGraphOptimizerSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Factor Graphs for Robot Perception (Dellaert & Kaess)', 'g2o: A General Framework for Graph Optimization (Kummerle et al.)'],
  },
  {
    id: '3d-gaussian-splatting-slam',
    slug: '3d-gaussian-splatting-slam',
    domain: 'advanced',
    level: 10,
    tier: 'Spatial Intelligence',
    titleEn: '3D Gaussian Splatting SLAM (3DGS-SLAM) & Radiance Fields',
    titleId: '3D Gaussian Splatting SLAM (3DGS-SLAM) & Radiance Fields',
    difficulty: 'Advanced',
    estimatedMinutes: 50,
    prerequisites: ['3d-lidar-and-vslam', 'factor-graph-optimization'],
    platforms: ['aerial', 'mobile', 'manipulator'],
    components: ['GaussianSplattingSlamSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['3D Gaussian Splatting for Real-Time Radiance Field Rendering (Kerbl et al.)', 'Gaussian Splatting SLAM (Matsuki et al.)'],
  },
  {
    id: 'sim-to-real-and-domain-randomization',
    slug: 'sim-to-real-and-domain-randomization',
    domain: 'advanced',
    level: 10,
    tier: 'Advanced Embodiments',
    titleEn: 'Sim-to-Real Transfer, Domain Randomization & Privileged RL',
    titleId: 'Sim-to-Real Transfer, Randomisasi Domain & Privileged RL',
    difficulty: 'Advanced',
    estimatedMinutes: 45,
    prerequisites: ['mathematical-foundations', 'legged-robotics-fundamentals'],
    platforms: ['legged', 'manipulator', 'aerial', 'mobile'],
    components: ['FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Domain Randomization for Transferring Deep Neural Networks (Tobin et al.)', 'Learning Agile and Dynamic Motor Skills for Legged Robots (Hwangbo et al.)'],
  },
  {
    id: 'vla-and-diffusion-policies',
    slug: 'vla-and-diffusion-policies',
    domain: 'advanced',
    level: 10,
    tier: 'Advanced Embodiments',
    titleEn: 'Vision-Language-Action (VLA) & Diffusion Policies for Robot Manipulation',
    titleId: 'Vision-Language-Action (VLA) & Diffusion Policy untuk Manipulasi Robot',
    difficulty: 'Advanced',
    estimatedMinutes: 50,
    prerequisites: ['2dof-inverse-kinematics', 'sim-to-real-and-domain-randomization'],
    platforms: ['manipulator', 'mobile', 'legged'],
    components: ['DiffusionPolicyVlaSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Diffusion Policy: Visuomotor Policy Learning via Action Diffusion (Chi et al.)', 'OpenVLA: An Open-Source Vision-Language-Action Model (Kim et al.)'],
  },
  {
    id: 'laplacian-consensus',
    slug: 'laplacian-consensus',
    domain: 'advanced',
    level: 18,
    tier: 'Advanced Embodiments',
    titleEn: 'Graph Laplacian Consensus & Swarm Coordination',
    titleId: 'Konsensus Graf Laplacian & Koordinasi Kawanan',
    difficulty: 'Advanced',
    estimatedMinutes: 45,
    prerequisites: ['mathematical-foundations', 'velocity-kinematics-2d'],
    platforms: ['aerial', 'mobile'],
    components: ['MultiAgentSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Consensus Problems in Networks of Agents (Olfati-Saber)'],
  },
  {
    id: 'formation-control-and-swarms',
    slug: 'formation-control-and-swarms',
    domain: 'advanced',
    level: 18,
    tier: 'Advanced Embodiments',
    titleEn: 'Formation Control & Leader-Follower Swarms (M26)',
    titleId: 'Kendali Formasi & Kawanan Robot Leader-Follower (M26)',
    difficulty: 'Advanced',
    estimatedMinutes: 45,
    prerequisites: ['laplacian-consensus', 'velocity-kinematics-2d'],
    platforms: ['aerial', 'mobile', 'marine'],
    components: ['FormationControlSimulator', 'FormulaExplainer', 'ConceptCheck'],
    interactive: true,
    references: ['Ren & Beard (2008). Distributed Consensus in Multi-Vehicle Cooperative Control. Springer.', 'Olfati-Saber (2006). Flocking for Multi-Agent Dynamic Systems. IEEE TAC.'],
  },
];

export function getLessonById(id: string): LessonRegistryItem | undefined {
  return LESSON_REGISTRY.find((l) => l.id === id);
}

export function getLessonsByDomain(domain: string): LessonRegistryItem[] {
  return LESSON_REGISTRY.filter((l) => l.domain === domain);
}

export function getLessonsByLevel(level: number): LessonRegistryItem[] {
  return LESSON_REGISTRY.filter((l) => l.level === level);
}

export function getLessonsByPlatform(platform: 'manipulator' | 'mobile' | 'aerial' | 'marine' | 'legged'): LessonRegistryItem[] {
  return LESSON_REGISTRY.filter((l) => l.platforms.includes(platform));
}
